var songs = [
"Kunstner","Navn","cd","kategori",
"ABBA","Dancing Queen","CD1",,
"ABBA","Take a Chance on Me","CD1",,
"ABBA","Mamma Mia","CD1",,
"ABBA","The Winner Takes It All","CD1",,
"ABBA","S.O.S.","CD1",,
"ABBA","Gimme! Gimme! Gimme! (A M…","CD1",,
"ABBA","Thank You for the Music","CD1",,
"ABBA","Waterloo","CD1",,
"ACDC","Back In Black","CD1",,
"ACDC","T.N.T.","CD1",,
"ACDC","Highway To Hell","CD1",,
"ACDC","Thunderstruck","CD1",,
"Ace Of Base","Life Is A Flower","CD1",,
"Ace Of Base","Cruel Summer (Big Bonus Mix)","CD1",,
"Ace Of Base","All That The Wants","CD1",,
"Ace Of Base","Whell Of Fortune","CD1",,
"Ace Of Base","The Sign","CD1",,
"Adam Lambert","Whataya Want From Me","CD2",,
"Aerosmith","Amazing","CD2",,
"Aerosmith","Dude (Looks Like a Lady)","CD2",,
"Aerosmith","Crying","CD2",,
"Aerosmith","Crazy","CD2",,
"Aerosmith","Jaded","CD2",,
"Aerosmith","(Water Song) Janie's Got A Gun","CD2",,
"AFI","Miss Murder","CD2",,
"Agnes","Release Me","CD2",,
"Agnes","On and On","CD2",,
"Aha","Take On Me","CD2",,
"Air/Beth Hirsch","All I Need","CD2",,
"Akon & Madonna","Celebration","CD2",,
"Akon Feat Kardinal Offishall An…","Beautiful","CD2",,
"Akon feat. Kardinal Offishal","Dangerous","CD2",,
"Akon Ft. Eminem","Smack That","CD2",,
"Alanis Morissette","Ironic","CD3",,
"Alanis Morissette","You Learn","CD3",,
"Alanis Morissette","Hand in My Pocket","CD3",,
"Alanis Morissette","All I Really Want","CD3",,
"Alanis Morissette","Right Through You","CD3",,
"Alanis Morissette","Head over Feet","CD3",,
"Alanis Morissette","Wake Up","CD3",,
"Alanis Morrisette","Not the Doctor","CD3",,
"Alanis Morrisette","Perfect","CD3",,
"Alanis Morrisette","You Oughta Know","CD3",,
"Alannah Myles","Black Velvet","CD3",,
"Alberte","Tænder På Et Kys",,,
"Alberte","Chevy 56",,,
"Alcazar","Crying At The Discoteque","CD3",,
"Alex Gaudino & Crystal Waters","Destination Calabria (Original…","CD3",,
"Alexandra Burke","All Night Long","CD3",,
"Alexandra Burke/Flo Rida","Bad Boys","CD3",,
"Alice Cooper","Poison","CD4",,
"Alice DJ","Better Off Alone","CD4",,
"Alice in Chains","Rooster","CD4",,
"Alicia Bridges","I Love The Nightlife","CD4",,
"Alicia Keys","Empire State Of Mind (Part II)…","CD4",,
"Alien Ant Farm","Smooth Criminal","CD4",,
"All Saints","Never Ever","CD4",,
"The All-American Rejects","Gives You Hell","CD4",,
"Alphabeat","Boyfriend","CD4",,
"Alphabeat","Heat Wave","CD4",,
"Alphabeat","The Spell","CD4",,
"Alphabeat","DJ","CD4",,
"Alphabeat","10000 Nights of Thunder","CD4",,
"Alphabeat","Fascination","CD4",,
"Alphaville","One Night in Bangkok","CD4",,
"Alphaville","Big in Japan","CD4",,
"Amy Winehouse","Rehab","CD5",,
"Amy Winehouse","You Know I'm No Good","CD5",,
"Amy Winehouse","Tears Dry On Their Own","CD5",,
"Amy Winehouse","Valerie","CD5",,
"Ana Johnsson","Don't Cry for Pain","CD5",,
"Anastacia","I'm Outta Love","CD5",,
"Anastacia","Left Outside Alone","CD5",,
"Anastacia","Paid My Dues","CD5",,
"Anden","Du er den Store Kærlighed","CD5",,
"Anden","Tag og Fuck af","CD5",,
"Anden","Quang","CD5",,
"Andrew Strong","Mustang Sally","CD5",,
"Ann Lee","2 Times","CD5",,
"Anna David","Fuck Dig","CD5",,
"Anna David","Når Musikken Spiller","CD5",,
"Anne Linnet","Tusind stykker","CD5",,
"Anne Linnet","Venus","CD5",,
"Anouk","Nobody's Wife","CD5",,
"Antiloop","In My Mind","CD6",,
"Antiloop","Believe","CD6",,
"Apollo 440","Ain't Talkin' Bout Dub","CD6",,
"Apollo Four Forty","Stop The Rock","CD6",,
"Aqua","Happy Boys & Girls","CD6",,
"Aqua","Barbie Girl","CD6",,
"Aqua","Doctor Jones","CD6",,
"Aqua","My Oh My","CD6",,
"Aqua","Roses Are Red","CD6",,
"Aqua","Lollipop (Candyman)","CD6",,
"Aqua","Cartoon Heroes","CD6",,
"Aqua","Back To The 80's (Single Versi…","CD6",,
"Arctic Monkeys","Fluorescent Adolescent","CD6",,
"Arctic Monkeys","I Bet You Look Good on the Da…","CD6",,
"Arctic Monkeys","Riot Van","CD6",,
"Arctic Monkeys","Dancing Shoes","CD6",,
"Arctic Monkeys","When the Sun Goes Down","CD6",,
"Aretha Franklin","Respect","CD7",,
"Aretha Franklin","Think","CD7",,
"Armand Van Helden","MyMyMy","CD7",,
"Arrested Development","people everyday","CD7",,
"Aslan","Crazy World","CD7",,
"Aswad","Shine","CD7",,
"Atomic Kitten","Eternal Flame","CD7",,
"Atomic Swing","Stone me Into the Groove","CD7",,
"Avril Lavigne","Girlfriend (Clean Edit)","CD7",,
"Avril Lavigne","Sk8ter Boi","CD7",,
"B.O.B Aka Bobby Ray Ft. Brun…","Nothin' On You","CD7",,
"B.O.B.","Airplanes Part 2 (ft. Eminem A…","CD7",,
"Babylon Zoo","Spaceman","CD7",,
"Baccara","Yes Sir, I Can Boogie","CD7",,
"Bachelor Girl","Busses and Trains","CD7",,
"Bachman-Turner Overdrive","You Ain't Seen Nothin' Yet","CD7",,
"Back to Back","Som De Andre Gør","CD8",,
"Back to Back","Jonathan","CD8",,
"Backstreet Boys","Quit Playing Games With My H…","CD8",,
"Backstreet Boys","We've Got It Goin' On","CD8",,
"Backstreet Boys","Everybody (Backstreet's Back)","CD8",,
"Backstreet Boys","Larger Than Life","CD8",,
"Backstreet Boys","I Want It That Way","CD8",,
"Backstreet Boys/Smooth T","Get Down (You're the One for…","CD8",,
"Baltimore","Tarzan Boy","CD8",,
"Bamses Venner","Hvorfor går Louise til bal","CD8",,
"Bamses Venner","I En Lille Båd Der Gynger","CD8",,
"Bamses Venner","Vimmersvej","CD8",,
"Bananarama","I'm Your Venus","CD8",,
"Bangles","Manic Monday","CD8",,
"Bare Naked Ladies","One Week","CD8",,
"Barry White","You're The First, The Last, My…","CD9",,
"Barry White","Can't Get Enough of Your Love","CD9",,
"Barry White","Let the Music Play","CD9",,
"Basement Jaxx","Red Alert (Jaxx Radio Mix)","CD9",,
"Basshunter","Boten Anna","CD9",,
"Bay City Rollers","I only want to be with you","CD9",,
"Beach Boys","Fun Fun Fun","CD9",,
"Beach Boys","Barbara Ann (Single Version)","CD9",,
"Beach Boys","The Lion Sleeps Tonight","CD9",,
"Beach Boys","Wouldn't it be Nice","CD9",,
"Beach Boys","Kokomo","CD9",,
"Beastie Boys","Sabotage","CD9",,
"Beastie Boys","Fight For Your Right","CD9",,
"Beastie Boys","Body Moving","CD9",,
"Beastie Boys","Intergalactic","CD9",,
"Beastie Boys","Girls","CD9",,
"Beatfreakz","Somebodys Watching Me","CD9",,
"Beatfreakz","Superfreakz","CD9",,
"The Beatles","Ticket To Ride","CD10",,
"The Beatles","The Fool On The Hill","CD10",,
"The Beatles","I Am The Walrus","CD10",,
"The Beatles","Strawberry Fields Forever","CD10",,
"The Beatles","Lucy In The Sky With Diamonds","CD10",,
"The Beatles","Revolution","CD10",,
"The Beatles","Can't Buy Me Love","CD10",,
"The Beatles","Hey Jude","CD10",,
"The Beatles","She Loves You","CD10",,
"The Beatles","All My Loving","CD10",,
"The Beatles","All You Need Is Love","CD10",,
"The Beatles","Daytripper","CD10",,
"The Beatles","A Hard Days Night","CD10",,
"The Beatles","With a Little Help From My Frie…","CD10",,
"The Beatles","I Wanna Hold Your Hand½","CD11",,
"The Beatles","Twist and Shout","CD11",,
"The Beatles","Yellow Submarine","CD11",,
"The Beatles","Yesterday","CD11",,
"The Beatles","Happy Birthday","CD11",,
"The Beatles","Penny Lane","CD11",,
"The Beatles","Back in the U.S.S.R.","CD11",,
"The Beatles","Ob-La-Di, Ob-La-Da","CD11",,
"The Beatles","Get Back","CD11",,
"The Beatles","Don't Let Me Down","CD11",,
"The Beatles","Come Together","CD11",,
"The Beatles","Octopus's Garden","CD11",,
"The Beatles","Let It Be","CD11",,
"Beck","Loser","CD12",,
"Bee Gees","Tragedy","CD12",,
"Bee Gees","Stayin' Alive","CD12",,
"Belinda Carlisle","Heaven Is A Place On Earth","CD12",,
"Belouis Some","Imagination","CD12",,
"Ben E. King","Stand By Me","CD12",,
"Benassi Bros feat.Dhany","Hit My Heart","CD12",,
"Benny Benassi","Satisfaction","CD12",,
"Bent Fabric","Jukebox","CD12",,
"Berlin","Take My Breath Away","CD12",,
"Beyonce","Baby Boy (feat. Sean Paul)","CD12",,
"Beyonce","Irreplaceable","CD12",,
"Beyonce","Naughty Girl","CD12",,
"Beyonce","Single Ladies (Put A Ring On It)","CD12",,
"Beyoncé","Check On It","CD12",,
"Big Fat Snake","No peace like in heaven","CD12",,
"Big Fat Snake","Big Boys In Red And White","CD12",,
"Bikstok Røgsystem","DK's Koner","CD13",,
"Bikstok Røgsystem","Fabrik","CD13",,
"Bikstok Røgsystem","Radio","CD13",,
"Bikstok Røgsystem","Penge på Græs","CD13",,
"Bill Conti","Dynasty","CD13",,
"Bill Haley","Rock Around the Clock","CD13",,
"Bill Monroe","Blue Moon Of Kentucky","CD13",,
"Billy Idol","You Spin Me Right Round","CD13",,
"Billy Idol","Uptown Girl","CD13",,
"Billy Ocean","When the Going Gets Tough","CD13",,
"Birthe Kjær","Pas på den knaldrøde gummibåd","CD13",,
"Birthe Kjær","Vi maler byen rød","CD13",,
"Birthe Kjær","Sommer og Sol","CD13",,
"Black Eyed Peas","I Gotta Feeling","CD14",,
"Black Eyed Peas","Meet Me Halfway","CD14",,
"Black Eyed Peas","Don't Phunk With My Heart","CD14",,
"Black Eyed Peas","Let's Get it Started","CD14",,
"Black Eyed Peas","Shut Up","CD14",,
"Black Eyed Peas","Where is the Love","CD14",,
"Black Eyed Peas","My Humps","CD14",,
"Black Lace","Agadoo","CD14",,
"Blackstreet","No Diggity","CD14",,
"Bli' Glad","Kærlighed Til Folket Feat. Pete…","CD14",,
"BliGlad!","Kærlighed Til Folket","CD14",,
"Blink 182","All the Small Things","CD14",,
"Blink 182","What's My Age Again","CD14",,
"Blondie","Call Me","CD14",,
"Blondie","One Way Or Another","CD14",,
"Blondie","Maria","CD14",,
"The Bloodhound Gang","Fire Water Burn (The Roof is o…","CD14",,
"Bloodhound Gang","Bad Touch","CD14",,
"Blue","Signed, Sealed, Delivered I'm…","CD15",,
"Blues Brothers","Everybody Needs Somebody t…","CD15",,
"Blues Brothers","Hit the Road Jack","CD15",,
"Blues Brothers","Soul Man","CD15",,
"Blues Brothers","Think","CD15",,
"Blur","Song 2","CD15",,
"Blur","Girls & Boys","CD15",,
"Blur","Country House","CD15",,
"Blur","Parklife","CD15",,
"Blå Øjne","Romeo","CD15",,
"Blå Øjne","Dig og Mig","CD15",,
"Bo","Don't Go","CD15",,
"Bob Marley","Buffalo Soldier","CD15",,
"Bob Marley","Is This Love","CD15",,
"Bob Marley","Jammin'","CD15",,
"Bob Marley","No Woman No Cry","CD15",,
"Bob Marley","I Shot the Sheriff","CD15",,
"Bob Marley","Sun is Shining (remix)","CD15",,
"Bob Sinclair","Love Is In the Air","CD16",,
"Bob Sinclair","Sound of Freedom","CD16",,
"Bob Sinclair","World Hold On","CD16",,
"Bob Sinclair","Love Generation","CD16",,
"Bob Sinclair","Rock This Party / Everybody D…","CD16",,
"Bobby McFerrin","Don't Worry Be Happy","CD16",,
"Bodyrockers","I Like The Way","CD16",,
"Bodyrox feat. Luciana","Yeah Yeah","CD16",,
"Bomfunk MCs","Freestyler","CD16",,
"Bon Jovi","Livin' On A Prayer","CD16",,
"Bon Jovi","Someday I'll Be Saturday Night","CD16",,
"Bon Jovi","it's my life","CD16",,
"Boney M","By the Rivers of Babylon","CD17",,
"Boney M","Daddy Cool","CD17",,
"Boney M","Brown Girl in the Ring","CD17",,
"Boney M.","Rivers of Babylon","CD17",,
"Boney M.","Daddy Cool","CD17",,
"Boney M.","Brown Girl in the Ring","CD17",,
"Boney M.","Ma Baker","CD17",,
"Boney M.","Hooray! Hooray! It's a Holi-Holi…","CD17",,
"The Boo Radleys","Wake Up Boo!","CD17",,
"The Boomtown Rats","I Don T Like Mondays","CD17",,
"Booty Bass","Shake That Ass Bitch","CD17",,
"Boston","More Than a Feeling","CD17",,
"Bowling for Soup","1985","CD17",,
"Brandy/Monica","The Boy Is Mine","CD17",,
"Brian McFadden/Delta Goodrem","Almost Here","CD17",,
"Britney and Madonna","Me Against the Music","CD18",,
"Britney Spears","Gimme More","CD18",,
"Britney Spears","Piece Of Me","CD18",,
"Britney Spears","Toxic","CD18",,
"Britney Spears","Baby One More Time","CD18",,
"Britney Spears","Oops! ... I Did It Again","CD18",,
"Britney Spears","Stronger","CD18",,
"Britney Spears","My Prerogative","CD18",,
"Britney Spears","Megamix","CD18",,
"Britney Spears","Womanizer","CD18",,
"Britney Spears feat.T.I.","Gimme More Remix","CD18",,
"Brixx","Video Video","CD18",,
"Bruce Springsteen","The River","CD18",,
"Bruce Springsteen","Dancing in the Dark","CD18",,
"Bruce Springsteen","Born In The Usa","CD18",,
"Det Brune Punktum","Jeg Vil i Seng Med de Fleste","CD28","OBS",
"Det Brune Punktum","Numsesangen","CD28","OBS",
"Det Brune Punktum","Ud I Det Blå","CD28","OBS",
"Det Brune Punktum","For Kendt Til Det Her Sted","CD28","OBS",
"Bruno Mars","Just the Way You Are","CD18",,
"Bryan Adams","Run To You","CD19",,
"Bryan Adams","Can't Stop This Thing We Started","CD19",,
"Bryan Adams","The Only Thing That Looks Go…","CD19",,
"Bryan Adams","(Everything I Do) I Do It For Yo…","CD19",,
"Bryan Adams","Summer of '69","CD19",,
"Bryan Adams & Tina Turner","It's Only Love","CD19",,
"Bryan Adams and Melanie C","When You're Gone","CD19",,
"Bryan Adams/Rod Stewart/Sting","All for Love","CD19",,
"Brødrende Olsen","Smuk Som et Stjerneskud","CD19",,
"Buckcherry","Crazy Bitch","CD19",,
"Buggles","Video Killed the Radio Star","CD19",,
"Burhan G","Jeg Vil Ha' Dig For Mig Selv","CD19",,
"Burhan G","Mest Ondt Feat. Medina","CD19",,
"Burhan G","Tættere på Himlen Feat. Nik O…","CD19",,
"Burhan G","Burhan G","CD19",,
"Bus Stop feat. Carl Douglas","Kung Fu Fighting","CD19",,
"C & C Music Factory","Gonna Make You Sweat (Ever…","CD20",,
"C.J. Lewis","Sweets For My Sweet","CD20",,
"C21","She Cries","CD20",,
"The Calling","Adrianne","CD20",,
"Calvin Harris","Im Not Alone","CD20",,
"Camarco","I Promised Myself","CD20",,
"Cameo","Word Up","CD20",,
"Captain & Tenille","Love Will Keep Us Together","CD20",,
"The Cardigans","Erase-Rewind","CD20",,
"The Cardigans","My Favourite Game","CD20",,
"Cargo","Porn Star","CD20",,
"Carl Petter","Stik mig en øl","CD20",,
"Carpark North","Transparent And Glasslike","CD20",,
"Carpark North","Save me from Myself","CD20",,
"Carpark North","Shall We Be Gratefull","CD20",,
"Cartoons","Doodah","CD21",,
"Cartoons","Witchdoctor","CD21",,
"Cascada","Evacuate The Dancefloor","CD21",,
"Celin Dion","My Heart Will Go On","CD21",,
"Celina Ree","Når Du Rør Ved Mig","CD21",,
"Chaka Khan","I'm Every Woman","CD21",,
"Chamillionaire","Riding Dirty","CD21",,
"The Chemical Brothers","Hey Boy Hey Girl","CD21",,
"The Chemical Brothers","Galvanize","CD21",,
"The Chemical Brothers","Block Rocking Beats","CD21",,
"Cher","Walking in Memphis","CD21",,
"Cher","Believe","CD21",,
"Cher","If I Could Turn Back Time","CD21",,
"Cher","The Shoop Shoop Song (It's in…","CD21",,
"cheryl cole","fight for this love","CD21",,
"Chesney Hawkes","The One And Only","CD21",,
"Chic","Good Times","CD22",,
"Chic","Le Freak","CD22",,
"Chicane","SaltWater (Original Radio Edit)","CD22",,
"Chipmunk Feat. Esmee Denters","Until You Were Gone","CD22",,
"The Chordettes","Lollipop","CD22",,
"Chris Isaak","Wicked Game","CD22",,
"Christian","Du kan gøre hvad du vil","CD22",,
"Christian","Lirekassemanden","CD22",,
"Christian Brøns","Bedst Når Vi Er To","CD22",,
"Christian Walz","Wonderchild","CD22",,
"Christina Aguilera","Keeps Gettin Better","CD22",,
"Christina Aguilera","Stronger","CD22",,
"Christina Aguilera","Not Myself Tonight","CD22",,
"Christina Aguilera","Carwash","CD22",,
"Christina Aguilera","Candyman","CD22",,
"Christina Aguilera","Dirty","CD22",,
"Christina Aguilera","Ain't No Other Man","CD22",,
"Christina Aguilera & co.","Lady Marmalade","CD22",,
"Chubby Checker","Let's Twist Again (New Version)","CD23",,
"Chubby Checker","Limbo Rock","CD23",,
"Chuck Berry","Johnny B. Good","CD23",,
"Chuck Berry/Jerome Patrick H…","Jack Rabbit Slims Twist Conte…","CD23",,
"Chumbawamba","I Get Knocked Down","CD23",,
"Ciara Ft Justin Timberlake","Love Sex Magic (Main)","CD23",,
"Cindy Lauper","Girls Just Wanna Have Fun","CD23",,
"Clara Sofie og Rune RK","Når Tiden Går Baglæns","CD23",,
"The Clash","Should I Stay or Should I Go","CD23",,
"The Clash","Come On Eileen","CD23",,
"Clawfinger","Do What I Say","CD23",,
"Colbie Caillat","Bubbly","CD23",,
"Coldplay","Why Does it Always Rain on Me","CD23",,
"Coldplay","Viva La Vida","CD23",,
"Coldplay","Fix You","CD23",,
"Coldplay","Speed of Sound","CD23",,
"The Communards","Don't Leave Me This Way","CD23",,
"Cool T","Magic Key","CD24",,
"Coolio","Gangsta's Paradise","CD24",,
"Coolio","I'll See You When You Get There","CD24",,
"Coolio Feat. 40 Thevz","C U When U Get There","CD24",,
"Cornershop","Brim Full of Asha","CD24",,
"Corona","Try Me Out","CD24",,
"Corona","Because the Night Belongs to…","CD24",,
"Corona feat. Ice MC","The Rhythm Of The Night","CD24",,
"The Corrs","Breathless","CD24",,
"Counting Crows","Mr. Jones","CD24",,
"Counting Crows","Weather With You","CD24",,
"Craig David","7 Days","CD24",,
"Craig David","Rise And Fall [Feat. Sting]","CD24",,
"Craig David","What's Your Flava","CD24",,
"Craig David","Walking Away","CD24",,
"Craig David and Artful Dodger","Re Rewind","CD24",,
"The Cranberries","Zombie","CD24",,
"Crash Test Dummies","Afternoons & Coffeespoons","CD25",,
"Crash Test Dummies","God Shuffled His Feet","CD25",,
"Crash Test Dummies","mmm mmm mmm mmm","CD25",,
"Crazy Town","Revolving Door","CD25",,
"Crazy Town","Butterfly","CD25",,
"CREEDENCE C. REVIVAL","BAD MOON RISING","CD25",,
"CREEDENCE C. REVIVAL","DOWN ON THE CORNER","CD25",,
"CREEDENCE C. REVIVAL","FORTUNATE SON","CD25",,
"CREEDENCE C. REVIVAL","HAVE YOU EVER SEEN THE…","CD25",,
"CREEDENCE C. REVIVAL","PROUD MARY","CD25",,
"Culture Beat","Anything","CD25",,
"Culture Beat","Mr Vain","CD25",,
"Culture Club","Karma Kameleon","CD25",,
"The Cure","Friday I'm in Love","CD25",,
"Cut'n'Move","Give it up","CD25",,
"Cut'n'Move","Get Serious","CD25",,
"Cutting Crew","I Just Died In Your Arms Tonight","CD25",,
"Cypress Hill","Insane in the Brain","CD25",,
"D-A-D","Grow Or Pay","CD26",,
"D:A:D","Bad Craziness","CD26",,
"D:A:D","Sleeping My Day Away","CD26",,
"D:A:D","Empty Heads","CD26",,
"D:A:D","Home Alone 4","CD26",,
"D:A:D","Laugh'n'a Half","CD26",,
"D:A:D","Nineteenhundredandyesterday","CD26",,
"D:A:D","Soft Dogs","CD26",,
"D12/Eminem","Stan","CD26",,
"Daddy Yankee","Gasolina (remix)","CD26",,
"Daft Punk","Around the World","CD26",,
"Daft Punk","One More Time","CD26",,
"Daft Punk","Put Your Hands Up in the Air","CD26",,
"Daft Punk","Music Sounds Better With You","CD26",,
"Daniel Powter","Bad Day","CD26",,
"Danseorkestret","Regndans","CD27",,
"Danseorkestret","Kom Tilbage Nu","CD27",,
"Danser Med Drenge","Hvor Længe Vil Du Ydmyge Dig","CD27",,
"Danser Med Drenge","Indianer","CD27",,
"Dante Thomas","Miss California","CD27",,
"Danzel","Pump It Up","CD27",,
"Dario G","Carnaval de Paris","CD27",,
"The Darkness","I Believe in a Thing Called Love","CD27",,
"Darude","Sandstorm","CD27",,
"David Bowie","China Girl","CD27",,
"David Guetta","Memories (Featuring Kid Cudi)","CD27",,
"David Guetta","Sexy Bitch (Featuring Akon)","CD27",,
"David Guetta","Love is gone (Fred Rister & Jo","CD27",,
"David Guetta","Baby When the Lights Go Out","CD27",,
"David Guetta","Love Don't Let Me Go","CD27",,
"David Guetta","When Love Takes Over (feat.…","CD27",,
"David Guetta feat. Chris Willis","Gettin Over You (Extended Mix)","CD27",,
"Def Leppard","Pour Some Sugar On Me","CD27",,
"Depeche Mode","Personal Jesus","CD28",,
"Depeche Mode","Enjoy the Silence","CD28",,
"Depeche Mode","I Just Can't Get Enough","CD28",,
"Des'ree","Life","CD28",,
"Desree","You Gotta Be","CD28",,
"Destiny's Child","Independent Women, Pt. 1","CD28",,
"Destiny's Child","Say My Name","CD28",,
"Destiny's Child","Jumpin' Jumpin'","CD28",,
"Destiny's Child","Survivor","CD28",,
"Destiny's Child","Bootylicious","CD28",,
"Diana Ross","Upside Down (Diana Ross)","CD29",,
"Diana Ross","Baby Love","CD29",,
"Diana Ross","I'm Coming Out","CD29",,
"Diana Ross","Ain't No Mountain High Enoug…","CD29",,
"Dimitri","Under Water","CD29",,
"Dionne Warwick","I Say A Little Prayer For You","CD29",,
"Dionne Warwick","Walk on By","CD29",,
"Dionne Warwick","Raindrops Keep Falling on My…","CD29",,
"Dire Straits","Sultans Of Swing","CD29",,
"Dire Straits","Walk Of Life","CD29",,
"Dire Straits","Money For Nothing","CD29",,
"Dirty Dancing","I've Had the Time of My Life","CD29",,
"Dizzee Rascal And Armand Va…","Bonkers","CD29",,
"Dizzy Mizz Lizzy","Waterline","CD30",,
"Dizzy Mizz Lizzy","Silverflame","CD30",,
"Dizzy Mizz Lizzy","Love is a Losers Game","CD30",,
"Dizzy Mizz Lizzy","67 Seas in Your Eyes","CD30",,
"Dizzy Mizz Lizzy","Barbedwired Baby's Dream","CD30",,
"DJ Dado","X-Files","CD30",,
"Dj Dex","It Just Wont Do","CD30",,
"DJ Quicksilver","Belissima","CD30",,
"DJ Sammy","Heaven","CD30",,
"DJ Ötzi","Burger Dance","CD30",,
"DJ Ötzi","Hey Baby","CD30",,
"DJ Ötzi","Anton Aus Tyrol","CD30",,
"DMX","Party Up (Up In Here)","CD30",,
"Dodo + VM Landsholdet","Vi vil ha' sejren i land","CD31",,
"Dodo and the Dodos","Giv mig hvad du har","CD31",,
"Dodo and the Dodos","Vågner i Natten","CD31",,
"Dodo and the Dodos","Sømand af Verden","CD31",,
"Dodo and the Dodos","Jeg Vil la' Lyset Brænde","CD31",,
"Dodo and the Dodos","Lev Livet Nu","CD31",,
"Dolly Parton","Jolene","CD31",,
"Dolly Parton","Working 9 to 5","CD31",,
"Dolly Parton","Applejack","CD31",,
"Don McLean","Bye Bye Miss American Pie","CD31",,
"Donna Summer","Hot Stuff","CD31",,
"Donna Summer","Knock on Wood","CD31",,
"Doobie Brothers","Long Train Running","CD31",,
"The Doors","Light My Fire","CD31",,
"The Doors","Break On Through","CD31",,
"The Doors","Alabama Song","CD31",,
"Dr. Alban","Look Whos Talking","CD32",,
"Dr. Alban","Let the beat go on","CD32",,
"Dr. Alban","Sing Hallelujah","CD32",,
"Dr.Alban","It's my Life","CD32",,
"Dr.Dre","Forgot About Dre","CD32",,
"Dr.Dre feat. Snoop Dog","Still Dre","CD32",,
"Dr.Dre feat. Snoop Dog","The Next Episode","CD32",,
"Drake","Find Your Love","CD32",,
"Drengene Fra Angora","Jul I Angora","CD32",,
"Drengene Fra Angora","Rejsesangen","CD32",,
"Drengene fra Angora","De Skal Ha' Baghjul","CD32",,
"Drengene fra Angora","Gummi - nej tak","CD32",,
"Drengene fra Angora","Kun Minderne Tilbage","CD32",,
"Drengene fra Angora","Har Jeg et Bildæk","CD32",,
"Drengene fra Angora","Hun Har en Pik","CD32",,
"Drengene fra Angora","Øresundsvisen","CD32",,
"Drømhus","Vill Ha Dig","CD32",,
"The Dubliners","Whiskey in the Jar","CD33",,
"The Dubliners","The Wild Rover","CD33",,
"Duffy","Warwick Avenue","CD33",,
"Duffy","Stepping Stone","CD33",,
"Duffy","Mercy","CD33",,
"Duran Duran","View to a Kill","CD33",,
"Duran Duran","Wild Boys","CD33",,
"Dusty Springfield","Son of a Preacher Man","CD33",,
"E-Type","Here I go again","CD33",,
"E-Type","Set the World on Fire","CD33",,
"E-Type","This Is the Way","CD33",,
"E-Type","Angels Crying","CD33",,
"Eagle Eye Cherry","Long Way Around","CD33",,
"Eagle Eye Cherry","Save Tonight","CD33",,
"Eagle Eye Cherry","Are You Still Having Fun","CD33",,
"Eagles","Hotel California","CD33",,
"Earth, Wind & Fire","Boogie Wonderland","CD34",,
"East 17","Stay Another Day","CD34",,
"East 17","Its Alright","CD34",,
"Eddie Grant","Gimme Hope Jo'anna","CD34",,
"Eddie Grant","Electric Avenue","CD34",,
"Edward Maya and Vika Jigulina","Stereo Love (Original Mix)","CD34",,
"Edwin collins","A Girl Like You","CD34",,
"Edwyn Collins","A Girl Like You","CD34",,
"Eiffel 65","Blue (Da Ba Dee)","CD34",,
"Eliza Doolittle","Pack Up","CD34",,
"Elton John","Nikita","CD34",,
"Elton John","Rocket Man (I Think Its Going…","CD34",,
"Elton John","Your Song","CD34",,
"Elton John","Lucy in the Sky With Diamonds","CD34",,
"Elton John","I'm Still Standing","CD34",,
"Elton John/RuPaul","Don't Go Breaking My Heart","CD34",,
"Elvis","Blue Suede Shoes","CD35",,
"Elvis","Don't Be Cruel","CD35",,
"Elvis","Hound Dog","CD35",,
"Elvis","In the Ghetto","CD35",,
"Elvis","Jailhouse Rock","CD35",,
"Elvis","I Can't Help Falling In Love Wit…","CD35",,
"Elvis","Return to Sender","CD35",,
"Elvis","Viva Las Vegas","CD35",,
"Elvis","Love me Tender","CD35",,
"Elvis Presley","(You're the) Devil in disguise","CD35",,
"Elvis Vs JXL","A Little Less Conversation","CD35",,
"Eminem","We Made You","CD35",,
"Eminem","Cleanin Out My Closet","CD35",,
"Eminem","Like Toy Soldiers","CD35",,
"Eminem","The Way I Am","CD35",,
"Eminem","The Real Slim Shady","CD35",,
"Eminem","Not Afraid","CD35",,
"Eminem","My Name Is","CD35",,
"Eminem; Rihanna","Love The Way You Lie","CD35",,
"Enigma","The Return to Innosence","CD36",,
"Enrique Iglesias","Do you Know (the Ping Pong S…","CD36",,
"Enrique Iglesias","Escape","CD36",,
"Enrique Iglesias Feat. Pitbull","I Like It","CD36",,
"Enrique Iglesias Feat. Sarah C","Takin Back My Love","CD36",,
"Enur feat. Natasja","Calabria 2007","CD36",,
"Erasure","A Little Respect","CD36",,
"Eric Carmen","Hungry Eyes","CD36",,
"Eric Clapton","Wonderful Tonight","CD36",,
"Eric Clapton","Layla","CD36",,
"Eric Clapton","Cocaine","CD36",,
"Eric Prydz","Call on Me","CD37",,
"eric prydz","pjanoo","CD37",,
"Erik Hassle","Hurtful","CD37",,
"Erik Hassle","Don't Bring Flowers After I'm D…","CD37",,
"Estelle","American Boy (Ft. Kanye West)","CD37",,
"Eternal","I Wanna Be the Only One [Due…","CD37",,
"Europe","The Final Countdown","CD37",,
"Eurythmics","Sweet Dreams","CD37",,
"Eurythmics","Must Be Talking to an Angel","CD37",,
"Eurythmics","When Tomorrow Comes","CD37",,
"Eve","Let Me Blow Your Mind","CD37",,
"Eve and Alicia Keys","Gangsta Love","CD37",,
"Everything But The Girl","Missing","CD37",,
"EWF","Let's Groove Tonight","CD37",,
"EyeQ","I want what she's got","CD37",,
"F.R. David","Words Don't Come Easy","CD38",,
"Fairground Attraction","Perfect","CD38",,
"Faithless","God is a DJ","CD38",,
"Fall Out Boy","This Aint a Scene","CD38",,
"Fat Joe feat. Ashanti","What's Luv","CD38",,
"FatBoy Slim","Dont Let The Man (Radio Edit)","CD38",,
"Fatboy Slim","Praise You","CD38",,
"Fatboy Slim","Ya Mama","CD38",,
"Fatboy Slim","Right Here, Right Now","CD38",,
"Fatboy Slim","The Rockafeller Skank","CD38",,
"Fatman Scoop","Be Faithful","CD38",,
"Fedde LeGrand","Put Your Hands Up For Detroit","CD38",,
"Fergie","London Bridge","CD38",,
"Fine Young Cannibals","She Drives Me Crazy","CD38",,
"Fleetwood Mac","Everywhere","CD38",,
"Fleetwood Mac","Little Lies","CD38",,
"Fleetwood Mac","Don't Stop","CD38",,
"Flo Rida","Low (Feat. T Pain)","CD39",,
"Flo Rida Feat. Ke$ha","Right Round","CD39",,
"Foo Fighters","The Pretender","CD39",,
"Foo Fighters","Best of You","CD39",,
"Foo Fighters","Everlong","CD39",,
"Foo Fighters","Learn to Fly","CD39",,
"Fool's Garden","Lemon Tree","CD39",,
"Foreigner","Cold As Ice","CD39",,
"Foreigner","I Want To Know What Love Is","CD39",,
"Four Tops","I Can't Help Myself","CD39",,
"Fragma","Tocas Miracle","CD39",,
"Frank Sinatra","Theme From New York, New Y…","CD39",,
"Frankie Goes To Hollywood","Relax","CD39",,
"Frankie Goes To Hollywood","The Power Of Love","CD39",,
"Frankie Valli","Grease","CD39",,
"Franz Ferdinand","Take Me Out","CD39",,
"The Fray","Over My Head [Cable Car]","CD39",,
"The Fray","How to Save a Life","CD39",,
"Freya","Yellow Ladybird","CD40",,
"The Fugees","Ready or Not","CD40",,
"The Fugees","Fu-Gee-La","CD40",,
"The Fugees","Killing Me Softly","CD40",,
"Gabriella Cilmi","Sweet About Me","CD40",,
"Gangway","My Girl & Me","CD40",,
"Garbage","Stupid Girl","CD40",,
"Gary Jules","Mad World","CD40",,
"Gary Moore","Still Got the Blues","CD40",,
"Gavin Degraw","Follow Through","CD40",,
"Gavin Degraw","I Don't Want To Be","CD40",,
"Gavin DeGraw","Chariot","CD40",,
"Gavin DeGraw","I Don't Wannna Be","CD40",,
"Genesis","Invisible Touch","CD40",,
"Genesis","Land of Confusion","CD40",,
"Genesis","I Can't Dance","CD40",,
"Genesis","Jesus He Knows Me","CD40",,
"George Harrison","I Got My Mind Set on You","CD41",,
"George Michael","Freedom","CD41",,
"George Michael","I Knew You Where Waiting","CD41",,
"George Michael","Faith","CD41",,
"George Thorogood & The Dest…","Bad To The Bone","CD41",,
"Gigi D'Agustino","L'amour Toujours","CD41",,
"Gigi D'Agustino","I'll Fly WIth You","CD41",,
"Gigi D'Agustino","La Passion","CD41",,
"Gina G","Ooh Aah, Just a Little Bit","CD41",,
"Ginuwine","Pony","CD41",,
"Glenn Frey","The Heat is On","CD41",,
"Gloria Estefan","Conga","CD41",,
"Gloria Gaynor","I Will Survive (remix)","CD41",,
"Gnags","Når jeg bliver gammel","CD42",,
"Gnags","Vilde Kaniner","CD42",,
"Gnags","Den Dejligste Morgen","CD42",,
"Gnags","Lygtemandens Sang","CD42",,
"Gnags","Mr. Swing King","CD42",,
"Gnarls Barkley","Crazy","CD42",,
"Goo Goo Dolls","Slide","CD42",,
"Goo Goo Dolls","Iris","CD42",,
"Good Charlotte","I Just Wanna Live","CD42",,
"Good Charlotte","Lifestyles of the Rich and Fam…","CD42",,
"Good Charlotte","Girls and Boys","CD42",,
"Gorillaz","Feel Good Inc.","CD42",,
"Gorillaz","Clint Eastwood","CD42",,
"Gorky Park","Bang","CD42",,
"Gossip","Heavy Cross","CD42",,
"Gramsespektrum","Vi Kaster Med Sten","CD42",,
"Grease","Grease Megamix","CD42",,
"Greenday","Boulevard of Broken Dreams","CD43",,
"Greenday","American Idiot","CD43",,
"Greenday","Basket Case","CD43",,
"Greenday","When I Come Around","CD43",,
"Greenday","Time of Your Life","CD43",,
"The Grid","Swamp thing","CD43",,
"Groove Armada","I See You Shaking That Ass","CD43",,
"Gry","Kloden Drejer","CD43",,
"Guns N' Roses","Welcome to the Jungle","CD43",,
"Guns N' Roses","Sweet Child O' Mine","CD43",,
"Guns N' Roses","Paradise City","CD43",,
"Guns N' Roses","Knockin' on Heaven's Door","CD43",,
"Guns'n'Roses","Don't Cry","CD43",,
"Guru Josh Project","Infinity 2008 (Klaas Vocal Edit)","CD43",,
"Gwen Stefani","What' You Waiting For?","CD43",,
"Gwen Stefani","The Sweet Escape","CD43",,
"Gwen Stefani","Hollaback Girl","CD43",,
"Gyllene Tider","Sommartider","CD43",,
"Haddaway","What Is Love","CD44",,
"Halberg Larsen -","Magi I Luften","CD44",,
"Hall & Oates","Maneater","CD44",,
"Hanne Boel","Don't know much about love","CD44",,
"Hanne Boel","(I Wanna) Make Love To You","CD44",,
"Hanson","Mmmbop","CD44",,
"Hej Matematik","Walkman","CD44",,
"Hej Matematik","Party i Provinsen","CD44",,
"Hermes House Band","Country Roads","CD44",,
"Hermes House Band","Hit The Road Jack","CD44",,
"Hermes House Band","I Will Survive","CD44",,
"Hermes House Band","Que Sera Sera","CD44",,
"Hermes House Bandand DJ O…","Live is Life [JB Mix]","CD44",,
"Herreys","Diggl.loo diggl.lay","CD44",,
"Holly Dolly","Dolly Song(the real)","CD44",,
"Holy Cows feat. A. Melin","Ooa hela natten","CD44",,
"Hoobastank","The reason","CD44",,
"Hot Chocolate","You Sexy Thing","CD45",,
"House Of Pain","Jump Around","CD45",,
"Hues Corporation","Rock The Boat","CD45",,
"Huey Lewis & the News","Hip to Be Square","CD45",,
"Huey Lewis & the News","The Power of Love","CD45",,
"Humleridderne","Humletid","CD45",,
"Humleridderne","Malerhjerne","CD45",,
"Humleridderne","Humle Bringer Hyggen","CD45",,
"Hurts","Wonderful Life","CD45",,
"Håkan Hellström","En Midsommarnattsdröm","CD45",,
"Ida Corr Vs Fedde Le Grand","Let Me Think About it","CD45",,
"Ida Maria","I Like You So Much Better Whe…","CD45",,
"Idaaida","En Klassiker","CD45",,
"Iggy Pop","Real Wild Child (Wild One)","CD45",,
"Iggy Pop","I'm a Passenger","CD45",,
"Ike & Tina Turner","Nutbush City Limits","CD45",,
"Incubus","Are You In?","CD46",,
"Infernal","Sorti De L'Enfer","CD46",,
"Infernal","Whenever You Need Me","CD46",,
"Infernal","Love is All","CD46",,
"Infernal","From Paris to Berlin","CD46",,
"Infernal","Self Control","CD46",,
"Infernal","Ten Miles From You","CD46",,
"Ini Kamoze","Hotstepper","CD46",,
"Inna","Hot","CD46",,
"Inna","Amazing","CD46",,
"Inner Circle","Sweat (A La La La La Long)","CD46",,
"Inner Circle","Bad Boys","CD46",,
"Inxs","Need You Tonight","CD46",,
"Irene Cora","What a Feeling","CD46",,
"Irene Cora","Fame","CD46",,
"Iron Maiden","Fear Of The Dark","CD46",,
"Iron Maiden","The Number Of The Beast","CD46",,
"Iron Maiden","Run To The Hills","CD46",,
"Iron Maiden","Can I Play With Madness","CD46",,
"Jack Johnson","Banana Pancakes","CD47",,
"Jack White & Alicia Keys","Another Way to Die","CD47",,
"Jackie Wilson","Reet Petite","CD47",,
"The Jacksons","Can You Feel It","CD47",,
"Jacob Haugaard","Hammer hammer fedt (Vi vind…","CD47",,
"Jaki Graham","Ain't Nobody","CD47",,
"James Blunt","You're Beautiful","CD47",,
"James Brown","I Feel Good","CD47",,
"James Brown","Sex Machine","CD47",,
"James Brown","I'm a Soulman","CD47",,
"James Morrison","You Give Me Something","CD47",,
"James Morrison Feat. Nelly Fu…","Broken Strings","CD47",,
"Jamiroquai","Canned Heat (Album Edit)","CD47",,
"Jamiroquai","Cosmic Girl","CD47",,
"Jamiroquai","Virtual Insanity","CD47",,
"Jamiroquai","Deeper Underground","CD47",,
"Janet Jackson","Together again","CD48",,
"Janet Jackson","Whoops Now","CD48",,
"Janet Jackson/Michael Jackson","Scream","CD48",,
"Jason Derulo","Whatcha Say","CD48",,
"Jason Derulo","In My Head","CD48",,
"Jason Mraz","I'm Yours","CD48",,
"Jay Sean feat. Sean Paul","Do You Remember","CD48",,
"Jay Z","Hard Knock Life","CD48",,
"Jay Z/Linkin Park","99 Problems","CD48",,
"Jay-Z & Alicia Keys","Empire State Of Mind","CD48",,
"jay-z ft mr. hudson","young forever","CD48",,
"Jeff Buckley","Hallelujah","CD48",,
"Jefferson Starship","We Built This City","CD48",,
"Jennifer Lopez","If You Had My Love","CD48",,
"Jennifer Lopez","Let's Get Loud","CD48",,
"Jennifer Lopez/Jadakiss/Styles P","Jenny from the Block","CD48",,
"Jennifer Lopez/LL Cool J","All I Have","CD48",,
"Jerry Lee Lewis","Great Balls of Fire","CD49",,
"Jesper Lundgård","Hang On","CD49",,
"Jet","Are You Gonna Be My Girl","CD49",,
"Jimi Hendrix","Daytripper","CD49",,
"Jimmy Cliff","I Can See Clearly Now","CD49",,
"Joan Jett & The Blackhearts","I Love Rock And Roll","CD49",,
"Joan Osbourne","One Of Us","CD49",,
"Jock Jams","I Like to Move It","CD49",,
"Joe Cocker","Unchain My Heart","CD49",,
"Joe Cocker","Hot Town Summer in the City","CD49",,
"Joe Cocker","Leave Your Hat On","CD49",,
"Joey McIntyre","Stay the Same","CD49",,
"Joey Moe","Yo-Yo","CD49",,
"Joey Moe","Miss Copenhagen","CD49",,
"Joey Moe","Flip It (Like a DJ)","CD49",,
"John Denver","Leaving on a Jetplane","CD49",,
"John Farnham","You're the Voice","CD49",,
"John Lennon","Give Peace a Chance","CD50",,
"John Lennon","Happy Xmas (War Is Over)","CD50",,
"John Lennon","Jealous Guy","CD50",,
"John Lennon","Woman","CD50",,
"John Lennon","Imagine","CD50",,
"John Mayer","Who Says","CD50",,
"John Mayer","Waiting on the World To Change","CD50",,
"John Mayer","Gravity","CD50",,
"John Mayer","Stop This Train","CD50",,
"John Mayer","Clarity","CD50",,
"John Mayer","Bigger Than My Body","CD50",,
"John Mayer","Your Body Is a Wonderland","CD50",,
"John Mogensen","Der er Noget Galt i Danmark","CD50",,
"Johnny Cash","Ring of Fire","CD50",,
"Johnny Cash","I Walk the Line","CD50",,
"Johnny Deluxe","Elskovspony","CD50",,
"Johnny Deluxe","Vi Vil Ha' Mer","CD50",,
"Johnny Deluxe","Drømmer Jeg?","CD50",,
"Johnny Logan","Hold Me Now 2001","CD51",,
"Johnny Madsen","Færgemanden","CD51",,
"Johnny Mandel","Theme from M*A*S*H (Suicide…","CD51",,
"Johnny Reimar","Du burde købe dig en tyrolerhat","CD51",,
"Johnny Reimar","Sikken' fest","CD51",,
"Johnson","Teriyaki","CD51",,
"Johnson","Det Passer","CD51",,
"Johnson","Kig Forbi","CD51",,
"Joker, LOC, Niarn..","Havnen (remix)","CD51",,
"Jokeren","Spændt Op Til Røg (Bikstok R…","CD51",,
"Jokeren","Den Eneste Anden","CD51",,
"Jokeren","Bevar Christiania","CD51",,
"Jokeren","Gravøl","CD51",,
"Jokeren","Godt Taget","CD51",,
"Jon","right here next to you","CD51",,
"Jooks","Hun Vil Ha' en Rapper","CD52",,
"Jordin Sparks","No Air (Duet With Chris Brown)","CD52",,
"Jose González","Heartbeats","CD52",,
"Joshua Kadison","Jessie","CD52",,
"Journey","Don't Stop Believin'","CD52",,
"Journey","Open Arms","CD52",,
"Judge Jules","King of My Castle","CD52",,
"Julie","Every Little Part of Me","CD52",,
"Junior Senior","Move Your Feet","CD52",,
"Justin Timberlake","Love Stoned","CD52",,
"Justin Timberlake","What Goes Around...","CD52",,
"Justin Timberlake","Summer Love","CD52",,
"Justin Timberlake","Like I Love You","CD52",,
"Justin Timberlake","Cry Me a River","CD52",,
"Justin Timberlake","Rock Your Body","CD52",,
"Justin Timberlake/T.I.","My Love","CD52",,
"Justin Timberlake/Timbaland","Sexyback","CD52",,
"K-Ci & JoJo","All My Life","CD53",,
"K'naan","Wavin' Flag-(The Celebration…","CD53",,
"K'naan","Wavin' Flag (Original Version)","CD53",,
"Kaiser Chiefs","Everyday I Love You Less and…","CD53",,
"Kanye West","Stronger","CD53",,
"Kanye West","Good Life (Ft. T-Pain)","CD53",,
"Kanye West","Diamonds From Sierra Leone (…","CD53",,
"Kanye West","Love Lockdown","CD53",,
"Kanye West","Heartless","CD53",,
"Kanye West/Jamie Foxx","Gold Digger","CD53",,
"Kaoma","Lambada","CD53",,
"Kaos Krew","Plante Pikhoved (kneppesangen)","CD53",,
"Karen","I Nat","CD53",,
"Karen Busck & Erann DD","Hjertet Ser","CD53",,
"Kashmir","Mom in Love & Daddy in Space","CD53",,
"Kashmir","Lampshade","CD53",,
"Kashmir","Rocket Brothers","CD53",,
"Kate Nash","Foundations","CD53",,
"Kato","Desert Walk (Feat. Outlandish)","CD54",,
"Kato","It's My Life (Feat. Dr. Alban, To…","CD54",,
"Kato Feat. Jon","Turn The Lights Off","CD54",,
"Kato Feat. Jon","Remember My Name (Feat. Jon)","CD54",,
"Kato Feat. USO Og Johnson","Hey Shorty (Yeah Yeah Pt. II)","CD54",,
"Katrina & the Waves","I'm Walking on Sunshine","CD54",,
"Katrine","Ayo Technology","CD54",,
"Katy Perry","I Kissed a Girl","CD54",,
"Katy Perry","Hot N Cold","CD54",,
"Katy Perry","Teenage Dream","CD54",,
"Katy Perry","California Gurls Feat. Snoop D…","CD54",,
"Katy Perry & Timbaland","If We Ever Meet Again","CD54",,
"KC & The Sunshine Band","That's the Way I Like It","CD54",,
"KC & the Sunshine Band","Get Down Tonight","CD54",,
"KC & the Sunshine Band","Play That Funky Music","CD54",,
"Ke$ha","Take It Off","CD54",,
"Ke$ha","TiK ToK","CD54",,
"Ke$ha","Your Love is My Drug","CD54",,
"Keane","Somewhere Only We Know","CD55",,
"Kelis","Caught Out There","CD55",,
"Kelis","Milkshake","CD55",,
"Kelly Clarkson","I Do Not Hook Up","CD55",,
"Kelly Clarkson","Since U Been Gone","CD55",,
"Kelly Clarkson","Behind These Hazel Eyes","CD55",,
"Kelly Clarkson","My Life Would Suck Without You","CD55",,
"Kelly Roland","Commander","CD55",,
"Kenny & Lotte","Alt det som ingen ser","CD55",,
"Kenny Loggins","Playing With the Boys","CD55",,
"Kenny Loggins","Footloose","CD55",,
"Kenny Loggins","Danger Zone","CD55",,
"Kernkraft","Zombie (remix)","CD55",,
"Kevin Little","Turn Me On","CD55",,
"Kid Cudi Vs Crookers","Day 'N' Nite","CD55",,
"Kid Rock","All Summer Long","CD55",,
"The Killers","Human","CD55",,
"The Killers","Mr. Brightside","CD55",,
"The Killers","Somebody Told Me","CD55",,
"The Killers","When You Were Young","CD55",,
"Kim Larsen","Langebro","CD56",,
"Kim Larsen","Sømand om Bord","CD56",,
"Kim Larsen","Christianshavns Kanal","CD56",,
"Kim Larsen","De Smukke Unge Mennesker","CD56",,
"Kim Larsen","Den Allersidste Dans","CD56",,
"Kim Larsen","Familien Skal i Skoven","CD56",,
"Kim Larsen","Joanna","CD56",,
"Kim Larsen","Jutlandia","CD56",,
"Kim Larsen","Køb Bananer","CD56",,
"Kim Larsen","Midt Om Natten","CD56",,
"Kim Larsen","Papirsklip","CD56",,
"Kim Larsen","Susan Himmelblå","CD56",,
"Kim Larsen","This Is My Life","CD56",,
"Kim Larsen","Det Bedste Til Mig og Mine Ve…","CD56",,
"Kim Larsen","Om Lidt Blir Her Stille","CD56",,
"Kim Larsen","Hvis Din Far Gir Dig Lov","CD56",,
"Kim Larsen","Havaje","CD56",,
"Kim Larsen","Rita","CD56",,
"Kim Larsen","Vi Er Dem (Forklædt Som Vok…","CD56",,
"Kim Larsen","Flyvere I Natten","CD56",,
"Kim Larsen","Mig og Molly","CD56",,
"Kim Wilde","Kids in America","CD57",,
"Kings of Leon","Sex On Fire","CD57",,
"Kings of Leon","Use Somebody","CD57",,
"Kirsten & Søren","Sku' du spørg' fra no'en","CD57",,
"Kirsten & Søren","Det' lige det","CD57",,
"KNA Connected","FIBS Løgn og Latin","CD57",,
"The Knack","My Sharona","CD57",,
"The Knife","Heartbeats","CD57",,
"Kool & the Gang","Jungle Boogie","CD57",,
"Kool & the Gang","Lady's Night","CD57",,
"Kool & the Gang","She's Fresh","CD57",,
"Kool & the Gang","Celebration","CD57",,
"Kool & the Gang","Get Down on It","CD57",,
"Kraftwerk","Das Boot","CD57",,
"Kriss Kross","Jump","CD57",,
"Kylie Minogue","Red Blooded Woman","CD58",,
"Kylie Minogue","The Loco-Motion","CD58",,
"Kylie Minogue","Spinning Around","CD58",,
"Kylie Minogue","On a Night Like This","CD58",,
"Kylie Minogue","Can't Get You Out of My Head","CD58",,
"Kylie Minogue","In Your Eyes","CD58",,
"Kylie Minogue","2 Hearts","CD58",,
"Kylie Minogue and Robbie Willi…","Kids","CD58",,
"L.O.C","Superbia","CD58",,
"L.O.C","XXX Couture","CD58",,
"L.O.C.","Få din flask' på","CD58",,
"L.O.C.","Frk. Escobar","CD58",,
"L.O.C.","Drik Din Hjerne Ud","CD58",,
"L.O.C.","Absinthe","CD58",,
"L.O.C.","Pop er det du har","CD58",,
"L.O.C.","Inkarneret","CD58",,
"L.O.C.","Undskyld","CD58",,
"L.O.C.","Hvorfor Vil Du Ikk'","CD58",,
"La Bouche","Sweet dreams","CD59",,
"La Bouche","Be My Lover","CD59",,
"Laban","Hvor Skal Vi Sove i Nat","CD59",,
"Lady Antebellum","Need You Now","CD59",,
"Lady GaGa","Bad Romance (Radio)","CD59",,
"Lady GaGa","Paparazzi","CD59",,
"Lady GaGa","Poker Face","CD59",,
"Lady GaGa","Just Dance feat. Colby O'Donis","CD59",,
"Lady Gaga","Alejandro","CD59",,
"Lady Gaga","Telephone (featuring Beyonce)","CD59",,
"Laid Back","Sunshine Reggae","CD59",,
"Laid Back","White Horse","CD59",,
"Lars H.U.G.","Elsker dig for evigt","CD60",,
"Lars Lilholt","Kald det kærlighed","CD60",,
"Lars Lilholt Band","Onkel Christian","CD60",,
"Lars Lilholt band","Ofelia","CD60",,
"Las Ketchup","The Ketchup Song","CD60",,
"Laura Branigan","Self Control","CD60",,
"Laurent Wolf","No stress","CD60",,
"Lauryn Hill","Everything Is Everything","CD60",,
"Lauryn Hill","Doo Wop","CD60",,
"Led Zeppelin","Stairway To Heaven","CD60",,
"LENE MARLIN","Sitting Down Here","CD60",,
"Lene Marlin","Unforgivable Sinner","CD60",,
"Lenny Kravitz","Are You Gonna Go My Way","CD60",,
"Lenny Kravitz","Again","CD60",,
"Lenny Kravitz","Fly Away","CD60",,
"Lenny Kravitz","American Woman Bonus Track","CD60",,
"Lenny Kravitz","It Ain't Over 'til It's Over","CD60",,
"Lifehouse","Hanging by a Moment","CD61",,
"Lily Allen","Smile","CD61",,
"Lily Allen","Not Fair","CD61",,
"Lily Allen","LDN","CD61",,
"Limahl","Neverending Story","CD61",,
"Limp Bizkit","Behind Blue Eyes","CD61",,
"Limp Bizkit","My Generation","CD61",,
"Limp Bizkit","Rollin","CD61",,
"Linkin Park","One Step Closer","CD61",,
"Linkin Park","Crawling","CD61",,
"Linkin Park","In the End","CD61",,
"Linkin Park","Somwhere I Belong","CD61",,
"Linkin Park","Breaking The Habit","CD61",,
"Linkin Park","What I've Done","CD61",,
"Lionel Richie","Dancing on the Ceiling","CD61",,
"Liquido","Narcotic","CD61",,
"Lis Sørensen","Du Tænder Lys","CD62",,
"Lis Sørensen","Mine Øjne De Skal Se","CD62",,
"Lis Sørensen","Fuld Af Nattens Stjerner","CD62",,
"Lisa Loeb & Nine Stories","Stay","CD62",,
"Live Aid","We Are the World","CD62",,
"The Lively Ones","Surf Rider","CD62",,
"Lizzie","Ramt i natten (radio version)","CD62",,
"The Loft","City of Dreams","CD62",,
"Lone Kellerman & Rockbandet","Se Venedig og Dø","CD62",,
"Lonnie Devantier","Hallo Hallo","CD62",,
"Los Del Rios","Macarena","CD62",,
"Los Lobos","La Bamba","CD62",,
"Lou Reed","Perfect Day","CD62",,
"Louis Prima","Just a Gigolo-I Ain't Got Nobody","CD62",,
"Louis Prima, Sam Butera, Keel…","When You're Smiling/Sheik of…","CD62",,
"Loveshack","B52","CD63",,
"Lucy Pearl","Don't Mess With My Man","CD63",,
"The Luniz","I Got 5 On It","CD63",,
"Lutricia Mcneal","Ain't That Just The Way","CD63",,
"Lutricia McNeal","Stranded","CD63",,
"Lynyrd Skynyrd","Sweet Home Alabama","CD63",,
"M C Hammer","U Can't Touch This","CD63",,
"M People","One Night in Heaven","CD63",,
"M.I.A.","Paper Planes","CD63",,
"Mabel","Boom Boom","CD63",,
"Madness","Our House","CD63",,
"Madonna","Hung Up","CD64",,
"Madonna","Music","CD64",,
"Madonna","Like A Virgin","CD64",,
"Madonna","Into The Groove","CD64",,
"Madonna","Like A Prayer","CD64",,
"Madonna","Express Yourself","CD64",,
"Madonna","Material Girl","CD64",,
"Madonna","Papa Don't Preach","CD64",,
"Madonna","Lucky Star","CD64",,
"Madonna","Who's That Girl","CD64",,
"Madonna","Die Another Day","CD64",,
"Madonna","Celebration","CD64",,
"Madonna","4 Minutes","CD64",,
"Madonna","Hey Mr.DJ","CD64",,
"Madonna","Jump","CD64",,
"Maggie Reilly & Mike Oldfield","Moonlight Shadow","CD64",,
"Magic Affair","In the middle of the night","CD64",,
"Magtens Korridorer","Picnic (På Kastellet)","CD65",,
"Magtens Korridorer","Lorte Parforhold","CD65",,
"Malk De Koijn","Sneglzilla","CD65",,
"Malk De Koijn","Fågt Op I Skalle Remix 2001","CD65",,
"Malk De Koijn","Vi Tager Fuglen På Dig","CD65",,
"Malk De Koijn","Phantastisk","CD65",,
"Malk De Koijn","De Rigtige McCoys","CD65",,
"Malurt","Superlove","CD65",,
"The mamas and the papas","Dream a Little Dream","CD65",,
"The Mamas and the Papas","California Dreaming","CD65",,
"Manu Chao","Me Guatas Tu","CD65",,
"Mariah Carey","Dreamlover","CD65",,
"Mariah Carey","Heartbreaker","CD65",,
"Mariah Carey","Now That I Know","CD65",,
"Mariah Carey","All I Want For Christmas Is You…","CD65",,
"Marilyn Manson","Personal Jesus","CD66",,
"Marilyn Manson","Tainted Love","CD66",,
"Marilyn Manson","Sweet Dreams (Are Made Of T…","CD66",,
"Mario Winans/Puff Daddy","I Don't Wanna Know","CD66",,
"Mark Morrison","Return Of The Mack","CD66",,
"Marky Mark & The Funky Bunc…","Good Vibrations","CD66",,
"Maroon 5","Wake Up Call","CD66",,
"Maroon 5","Sunday Morning","CD66",,
"Maroon 5","This Love","CD66",,
"Martha and the Vandellas","Dancing in the Street","CD66",,
"The Marvelettes","Mr. Postman","CD66",,
"Marvin Gaye","I Heard it Through the Grapevine","CD66",,
"Marvin Gaye & Tammi Terrell","Ain't No Mountain High Enough","CD66",,
"Mary Mary","Shackles (Praise You)","CD66",,
"Maskinen","Alla Som Inte Dansar (våldtäkt…","CD66",,
"Matchbox 20","Closing Time","CD66",,
"Matchbox 20","Breakfast at Tiffanys","CD66",,
"Mathilde","Lotte hvor er du henne","CD67",,
"Mc Lyte","Cold Rock A Party (Bad Boy re…","CD67",,
"Mchael Learns to Rock","Sleeping Child","CD67",,
"Me & My","Dub-I-Dub","CD67",,
"Meat Loaf","I'd Do Anything For Love","CD67",,
"meatloaf","Meat Loaf - Rock & Roll Dream…","CD67",,
"Medina","Kun For Mig","CD67",,
"Medina","Ensom","CD67",,
"Medina","Vi To","CD67",,
"Medina","Velkommen Til Medina (Radio…","CD67",,
"Medina & L.O.C.","Kun for Dig","CD67",,
"Meja","All 'Bout The Money","CD67",,
"Men at Work","I Come From a Land Down Un…","CD67",,
"Metallica","One","CD68",,
"Metallica","Master of Puppets","CD68",,
"Metallica","Enter Sandman","CD68",,
"Metallica","Nothing Else Matters","CD68",,
"Metallica","Whisky in the Jar","CD68",,
"Metro Station","Shake It","CD68",,
"Mew","Special","CD68",,
"Mew","Snow Brigade","CD68",,
"MGMT","Kids","CD68",,
"MGMT","Time to Pretend","CD68",,
"Michael Falck","I Et Land Uden Høje Bjerge","CD68",,
"Michael Jackson","ABC [The Jackson 5]","CD69",,
"Michael Jackson","Bad","CD69",,
"Michael Jackson","Beat It","CD69",,
"Michael Jackson","Billie Jean","CD69",,
"Michael Jackson","Black Or White","CD69",,
"Michael Jackson","Blame It On The Boogie","CD69",,
"Michael Jackson","Dirty Diana","CD69",,
"Michael Jackson","Don't Stop Til' You Get Enough","CD69",,
"Michael Jackson","Jam","CD69",,
"Michael Jackson","Man In The Mirror","CD69",,
"Michael Jackson","Remember The Time","CD69",,
"Michael Jackson","Rock With You","CD69",,
"Michael Jackson","Smooth Criminal","CD69",,
"Michael Jackson","They Don't Care About Us","CD69",,
"Michael Jackson","Thriller","CD69",,
"Michael Jackson","Wanna Be Startin' Somethin'","CD70",,
"Michael Jackson","The Way You Make Me Feel","CD70",,
"Michael Jackson","Come Together","CD70",,
"Michael Jackson","D.S.","CD70",,
"Michael Jackson","Earth Song","CD70",,
"michael jackson","this is it","CD70",,
"Michael Jackson","Michael Jackson mix","CD70",,
"Michael Jackson","Don't Stop 'Till Get Enough","CD70",,
"Michael Jackson,Jackson 5 -","I want you back","CD70",,
"Michael Jackson/Michael Jack…","I Just Can't Stop Loving You","CD70",,
"Michael Learns to Rock","The Actor","CD70",,
"Michael Learns To Rock","That's Why (You Go Away)","CD70",,
"Michelle Branch","Everywhere","CD70",,
"Mika","Relax (Take It Easy)","CD71",,
"Mika","Big Girl (You Are Beautiful)","CD71",,
"Mika","Grace Kelly","CD71",,
"Mika","Lollipop","CD71",,
"Mika","Love Today","CD71",,
"Mike and the Mechanics","Looking Back Over My Shoulder","CD71",,
"Mike Posner","Cooler Than Me Single Mix","CD71",,
"Millie Small","My Boy Lollipop","CD71",,
"Miranda","Vamos A La Playa","CD71",,
"Moby","Natural Blues","CD71",,
"Moby","Porcelain","CD71",,
"Moby","In This World","CD71",,
"Modern Talking","You're My Heart, You're My So…","CD71",,
"Modern Talking","Brother Louie [New Version]","CD71",,
"Modern Talking","Cheri Cheri Lady [New Version]","CD71",,
"Modest Mouse","Dashboard","CD71",,
"Modjo","lady","CD72",,
"Moloko","Sing It Back (Boris Radio Edit)","CD72",,
"The Monkees","I'm a Believer","CD72",,
"Monty Python","Always Look On The Bright Sid…","CD72",,
"Moonjam","Gennem ild og vand","CD72",,
"Moonjam","Sarai","CD72",,
"Morten Breum","Højere Vildere (Feat. Rune RK)","CD72",,
"Morten Breum Feat. Nik Og Jay","Domestic","CD72",,
"Motley Crue","Girls, Girls, Girls","CD72",,
"Mousse T Vs Hot 'N' Juicy","Horny","CD72",,
"Mr. Big","Wild World","CD72",,
"Mr. Big","To Be With You","CD72",,
"Mr. Mister","Take These Broken Wings","CD72",,
"Mr. President","Coco Jamboo (Radio Version)","CD72",,
"Muse","Time Is Running Out","CD72",,
"Muse","Supermassive Black Hole","CD72",,
"Muse","Knights of Cydonia","CD72",,
"Muse","Starlight","CD72",,
"Muse","Uprising","CD72",,
"My Chemical Romance","Welcome to the Black Parade","CD73",,
"Mylo","Drop the Pressure","CD73",,
"N-Dubz","We Dance On","CD73",,
"N-Trance","Stayin' Alive","CD73",,
"Nabiha","Deep Sleep","CD73",,
"Nanna","Buster","CD73",,
"Natalie Cole","Wild Women Do","CD73",,
"Natalie Imbruglia","Torn","CD73",,
"Natasha Beddingfield","These Words","CD73",,
"Natasja","Gi Mig DK Tilbage","CD73",,
"Natasja","Ildebrand I Byen","CD73",,
"Natasja","Dig og Mig","CD73",,
"Natasja","Gi' Mig Danmark Tilbage","CD73",,
"Natasja","Ildebrand","CD73",,
"Natasja","Op Med Hovedet","CD73",,
"Natasja","Hej Mr.DJ","CD73",,
"Ne-Yo","Closer (Main)","CD74",,
"Neja","Restless","CD74",,
"Nelly Furtado","Promiscous","CD74",,
"Nelly Furtado","Maneater","CD74",,
"Nelly Furtado","Im like a bird","CD74",,
"Nelly Furtado","Say It Right","CD74",,
"Nena","99 Red Balloons","CD74",,
"Nena","99 Luftballons","CD74",,
"Nephew","Superliga","CD74",,
"Nephew","Byens Hotel","CD74",,
"Nephew","Igen og Igen og","CD74",,
"Nephew","Movieclip","CD74",,
"Nephew","The Danish Way To Rock","CD74",,
"Nephew","Wannabe Darth Vader","CD74",,
"Nephew","Worst'n'Best Case Scenario","CD74",,
"NEPHEW/Polarkreis 18 V","Allein, Alene","CD74",,
"NERD","She Wants to Move","CD75",,
"Niarn","Dobbelt A","CD75",,
"Niarn","Stikkersvin feat.L.O.C.","CD75",,
"Nice Device","Cool Corona (Could You Be Like","CD75",,
"Nice Little Penguins","Flying","CD75",,
"Nickelback","Someday","CD75",,
"Nickelback","How You Remind Me","CD75",,
"Nickelback","Photograph","CD75",,
"Nickelback","Rockstar","CD75",,
"Nightcrawlers","Push The Feeling On","CD75",,
"Nik & Jay","Endnu En","CD76",,
"Nik & Jay","En Dag Tilbage","CD76",,
"Nik & Jay","Gør Det Igen","CD76",,
"Nik & Jay","Lækker","CD76",,
"Nik & Jay","Hot","CD76",,
"Nik & Jay","Ryst Din Røv","CD76",,
"Nik & Jay","Lækker (remix)","CD76",,
"Nik & Jay","Lækker (Aqua remix)","CD76",,
"Nik & Jay","Boing!","CD76",,
"Nik & Jay","I love ya","CD76",,
"Nik & Jay feat. Alex","Hvad Nu Hvis","CD76",,
"Nik & Jay feat. Enur","Calabria/Boing 2006","CD76",,
"Nik Kershaw","I Wont Let the Sun Go Down o…","CD76",,
"Nik Kershaw","The Riddle","CD76",,
"Nik Kershaw","Wouldn't It Be Good","CD76",,
"Nirvana","Smells Like Teen Spirit","CD77",,
"Nirvana","In Bloom","CD77",,
"Nirvana","Come as You Are","CD77",,
"Nirvana","Rape me","CD77",,
"No Doubt","Don't Speak","CD77",,
"No Doubt","Hey Baby","CD77",,
"No Doubt","It's My Life","CD77",,
"No Doubt","Just a Girl","CD77",,
"No Doubt","Hella Good","CD77",,
"Noisettes","Don't Upset the Rythm","CD77",,
"NSYNC","Pop","CD77",,
"NSYNC","Girlfriend","CD77",,
"NSYNC","Bye Bye Bye","CD77",,
"NSYNC","I want you back","CD77",,
"Nu Generation","In your arms","CD77",,
"Oasis","Champagne Supernova","CD77",,
"Oasis","Wonderwall","CD77",,
"Oasis","Hold On","CD77",,
"The Offspring","Self Esteem","CD78",,
"The Offspring","Pretty Fly","CD78",,
"The Offspring","Why Don't You Get a Job","CD78",,
"The Offspring","The Kids Aren't Alright","CD78",,
"Olive","You're Not Alone","CD78",,
"One Republic","Stop And Stare","CD78",,
"One Two","Sket så tit","CD78",,
"One Two","Midt i en drøm","CD78",,
"One Two","Den bedste tid","CD78",,
"OneRepublic","All The Right Moves","CD78",,
"OneRepublic","Good Life","CD78",,
"Otto Brandenburg","Susanne, Birgitte og Hanne","CD78",,
"Otto Brandenburg","To Lys På Et Bord","CD78",,
"Outcast","Hey Ya","CD79",,
"The Outhere Brothers","Boom Boom Boom","CD79",,
"Outkast","Ms. Jackson","CD79",,
"Outkast","Roses","CD79",,
"Outlandish","Walou","CD79",,
"Outlandish","Guantanamo","CD79",,
"Outlandish","Aischa","CD79",,
"Owl City","Fireflies","CD79",,
"owl city","vanilla twilight","CD79",,
"Panic at the Disco","I Write Sins","CD79",,
"Panjabi MC","Mundian To Bach Ke","CD79",,
"Paolo Nutini","Jenny Don't Be Hasty","CD79",,
"Papkasseshow","Los mig hårdt i bollerne","CD79",,
"Paradisio","Bailando","CD79",,
"Patrick Hernandez","Born To Be Alive","CD79",,
"Patrick Swayze","She's Like the Wind","CD79",,
"Paul Johnson","Get Get Down","CD80",,
"Paul Simon","You Can Call Me Al","CD80",,
"Pearl Jam","Black","CD80",,
"Pearl Jam","Alive","CD80",,
"Pet Shop Boys","West End Girls","CD80",,
"Pet Shop Boys","Always On My Mind","CD80",,
"Pet Shop Boys","Go West","CD80",,
"Pet Shop Boys/Robbie Williams","She's Madonna","CD80",,
"Peter Andre","Mysterious Girl","CD80",,
"Peter Gabriel","Kiss That Frog","CD80",,
"Peter Gabriel","Sledgehammer","CD80",,
"Peter Gabriel & Kate Bush","Dont Give Up","CD80",,
"Phats & Small","Turn Around","CD80",,
"Phil Collins","Can't Stop Loving You","CD81",,
"Phil Collins","Sussudio","CD81",,
"Phil Collins","Against All Odds","CD81",,
"Phil Collins","In the Air Tonight","CD81",,
"Phil Collins","Long Long Way To Go","CD81",,
"Phil Collins","True Colours","CD81",,
"Phil Collins","Can't Hurry Love","CD81",,
"Pink","Funhouse","CD81",,
"Pink","Who Knew","CD81",,
"Pink","Dear Mr. President","CD81",,
"Pink","U + Ur Hand","CD81",,
"Pink","So What","CD81",,
"Pink","Stupid Girls","CD81",,
"Pink","Get the Party Started","CD81",,
"Pink","Don't Let Me Get Me","CD81",,
"Pink","I Don't Believe You","CD81",,
"Pink Floyd","Another Brick in the Wall","CD82",,
"The Pink Floyd","Wish You Were Here","CD82",,
"Pitbull","I Know You Want Me (Calle Oc…","CD82",,
"Pixie Lott","Mama Do","CD82",,
"Pixie Lott","Boys And Girls","CD82",,
"Plain White T's","Hey There Delilah","CD82",,
"Pockets","I Won't Be There Anymore","CD82",,
"POD","Youth of the Nation","CD82",,
"Pointer Sisters","I'm So Excited","CD82",,
"The Police","Roxanne","CD82",,
"The Police","Message in a Bottle","CD82",,
"The Police","Walking on the Moon","CD82",,
"The Police","Every Little Thing She Does Is…","CD82",,
"The Police","Don't Stand So Close To Me","CD82",,
"The Police","Every Breath You Take","CD82",,
"Poul Krebs","Sådan nogen som os","CD83",,
"Pras feat. Mya","Ghetto Superstar","CD83",,
"The Presidents of the USA","Peaches","CD83",,
"Pretenders","Don't Get Me Wrong","CD83",,
"Prince","The Most Beautiful Girl In The…","CD83",,
"Prince","Musicology","CD83",,
"Prince","Purple Rain","CD83",,
"Prince","1999","CD83",,
"Prince","When Doves Cry","CD83",,
"Prince & the Revolution","Kiss","CD83",,
"Prince & the Revolution","Raspberry Beret","CD83",,
"Private","My Secret Lover","CD83",,
"Private","Crucify My Heart","CD83",,
"The Proclaimers","500 Miles","CD83",,
"Prodigy","Breathe","CD84",,
"The Prodigy","Jericho","CD84",,
"The Prodigy","Voodoo People","CD84",,
"The Prodigy","Poison","CD84",,
"The Prodigy","No Good (lang)","CD84",,
"The Prodigy","Breathe","CD84",,
"The Prodigy","Firestarter","CD84",,
"Promoe","Svennebanan","CD84",,
"Puff Daddy","I'll Be Missing You (feat. Faith…","CD84",,
"Pulp","Disco 2000","CD84",,
"Pulp Fiction","Teenage Wedding","CD84",,
"The Pussycat Dolls","When I Grow Up","CD84",,
"The Pussycat Dolls","Sway (Bonus Track)","CD84",,
"The Pussycat Dolls","Buttons","CD84",,
"The Pussycat Dolls feat. Will.I.…","Beep","CD84",,
"The Pussycat Dolls/Busta Rhy…","Don't Cha (Featuring Busta Rh…","CD84",,
"På Slaget 12","Hjem til Århus","CD84",,
"Queen","Fat Bottom Girls","CD85",,
"Queen","I Want It All","CD85",,
"Queen","Radio Gaga","CD85",,
"Queen","Somebody to Love","CD85",,
"Queen","Bohemain Rapsody","CD85",,
"Queen","Don't Stop Me Now","CD85",,
"Queen","Another One Bites the Dust","CD85",,
"Queen","Crazy Little Thing Called Love","CD85",,
"Queen","Show Must Go On","CD85",,
"Queen","We Will Rock You","CD85",,
"Queen","We Are The Champions","CD85",,
"queen/Freddie Mercury","Living On My Own","CD85",,
"Rachel Stevens","Sweet Dreams My LA Ex","CD85",,
"Radiohead","Karma Police","CD85",,
"Radiohead","Creep","CD85",,
"Rage Against the Machine","Bulls on Parade","CD86",,
"Rage Against The Machine","Killing In The Name Of","CD86",,
"Rage Against The Machine","Fistfull Of Steel","CD86",,
"Rage Against the Machine","Bombtrack","CD86",,
"RamJam","Black Betty","CD86",,
"Rammstein","Amerika","CD86",,
"Rammstein","Du Hast","CD86",,
"The Rapsody feat. Warren G &…","Prince Igor","CD86",,
"Rascal Flatts","Life Is a Highway","CD86",,
"The Rasmus","In The Shadows","CD86",,
"Rasmus Nøhr","Sommer i Europa","CD86",,
"Rasmus Nøhr","Søndag","CD86",,
"Rasmus Seebach","Engel","CD86",,
"Rasmus Seebach","Lidt I Fem","CD86",,
"Rasmus Seebach","Glad Igen","CD86",,
"Rasmus Seebach","Natteravn (Providers Vs. Rasm…","CD86",,
"Ray Charles","Hit the Road Jack","CD87",,
"ray charles/Keiji Haino/Peter B…","mess around","CD87",,
"ray charles/Keiji Haino/Peter B…","i've got a woman","CD87",,
"Ray Dee Ohh","Efterår","CD87",,
"Ray Dee Ohh","Mandags Stævnemøde","CD87",,
"Ray Dee Ohh","Elskes af Dig","CD87",,
"Razorlight","In The Morning","CD87",,
"Razorlight","America","CD87",,
"The Red Hot Chili Peppers","Scar Tissue","CD87",,
"Red Hot Chili Peppers","Can't Stop","CD87",,
"Red Hot Chili Peppers","Road Trippin'","CD87",,
"Red Hot Chili Peppers","Californication","CD87",,
"Red Hot Chili Peppers","Dani California","CD87",,
"Red Hot Chili Peppers","Give it Away","CD87",,
"Red Hot Chili Peppers","Snow","CD87",,
"Rednex","Cotton-Eye Joe","CD87",,
"Reef","Place Your Hands","CD87",,
"REM","Man On The Moon","CD88",,
"REM","Bad Day","CD88",,
"REM","What's The Frequency, Kenneth?","CD88",,
"REM","Losing My Religion","CD88",,
"REM","Imitation Of Life","CD88",,
"REM","Animal","CD88",,
"REM","Everybody Hurts","CD88",,
"Remady","No Superstar","CD88",,
"The Rembrandts","I'll Be There For You","CD88",,
"Rent Mel","Ta' det af","CD88",,
"Richard Marx","Right Here Waiting","CD88",,
"Richera","Vamos A La Playa","CD88",,
"Rick Astley","Never Gonna Give You Up","CD88",,
"Rick James","Super Freak","CD88",,
"Ricky Martin","She Bangs","CD88",,
"Ricky Martin","Olé Olé","CD88",,
"Right Said Fred","I'm Too Sexy","CD88",,
"Rihanna","Umbrella (Feat. Jay-Z)","CD89",,
"Rihanna","Don't Stop The Music","CD89",,
"Rihanna","Disturbia","CD89",,
"Rihanna","Take A Bow","CD89",,
"Rihanna","Only Girl (In The World) (Radio…","CD89",,
"Rihanna","Rude Boy","CD89",,
"Rihanna","SOS","CD89",,
"Rihanna","Te Amo","CD89",,
"Rihanna","Pon De Replay","CD89",,
"Rihanna","Russian Roulette","CD89",,
"Rob Thomas/Santana","Smooth","CD89",,
"Robbie Willams","Tripping","CD90",,
"Robbie Williams","Bodies","CD90",,
"Robbie Williams","Feel","CD90",,
"Robbie Williams","Come Undone","CD90",,
"Robbie Williams","Strong","CD90",,
"Robbie Williams","Millennium","CD90",,
"Robbie Williams","Let Me Entertain You","CD90",,
"Robbie Williams","Angels","CD90",,
"Robbie Williams","Rock DJ","CD90",,
"Robbie Williams","Bongo Bong (Je Ne Taime Plus)","CD90",,
"Robert Palmer","Addicted to Love","CD90",,
"Robyn","Dancing on My Own","CD90",,
"Robyn","Hang With Me","CD90",,
"Robyn","Do You Really Want Me","CD90",,
"Robyn","Don't Stop the Music","CD90",,
"Robyn","Show Me Love","CD90",,
"Robyn with Kleerup","With Every Heartbeat","CD90",,
"Rocazino","Elsk mig i nat","CD91",,
"Rocazino","Ridder Lykke","CD91",,
"Rocazino","All My Love","CD91",,
"Rocazino og Frank Arnesen","Én For Alle","CD91",,
"Rock Steady Crew","Hey You Rock Steady Crew","CD91",,
"Rockers By Choice","Jeg Er Skizofren ( Det' Jeg Osse)","CD91",,
"Rockers By Choice","Min Gamle Skole","CD91",,
"Rolling Stones","Sympathy For The Devil","CD91",,
"Rolling Stones","She's a Rainbow","CD91",,
"Rolling Stones","Paint It Black","CD91",,
"Rolling Stones","Satisfaction","CD91",,
"Rolling Stones","Start Me Up","CD91",,
"Rollo & King","Ved Du Hvad Hun Sagde","CD91",,
"Rollo & King","Dyt i Bamsen","CD91",,
"The Roots","The Seeds","CD91",,
"Roxette","Joyride","CD92",,
"Roxette","The Look","CD92",,
"Roxette","Dangerous","CD92",,
"Roxette","Listen To Your Heart","CD92",,
"Roxette","It Must Have Been Love","CD92",,
"Roxette","How Do You Do","CD92",,
"Roxette","Sleeping in My Car","CD92",,
"Roy Orbison","Pretty Woman","CD92",,
"Royksopp","What Else Is There- (Trentemo…","CD92",,
"Rufus Feat. Chaka Khan","Ain't Nobody","CD92",,
"Rugsted & Kreutzfeldt","Jeg ved det godt","CD92",,
"Run 4 fun","Please don't talk to Jessica","CD92",,
"Run D.M.C & Aerosmith","Walk This Way","CD92",,
"Run D.M.C vs Jason Nevins","It's like that","CD92",,
"Run D.M.C.","King of Rock","CD92",,
"Run D.M.C.","My Adidas","CD92",,
"Run D.M.C. vs. Jason Nevins","It's Tricky","CD92",,
"S.O.A.P.","S.O.A.P. Is In The Air","CD93",,
"S.O.A.P.","This Is How We Party","CD93",,
"S.O.A.P.","Ladidi Ladida","CD93",,
"Sabrina","Boys (Summertime Love)","CD93",,
"Safri Duo","All The People in the World","CD93",,
"Safri Duo","Played A Live","CD93",,
"Salt 'N' Pepa","Push It","CD93",,
"Salt'n'Pepa","Lets Talk About Sex","CD93",,
"Sam Sparro","Black And Gold","CD93",,
"Samantha Fox","Touch Me","CD93",,
"The Sandmen","Don't Let Me Down","CD93",,
"The Sandmen","5 Minutes Past Loneliness","CD93",,
"Sanne Salomonsen","Det er ikke det du siger","CD93",,
"Sanne Salomonsen","Where Blue Begins","CD93",,
"Sanne Salomonsen","Taxa","CD93",,
"Sanne Salomonsen","Kærligheden Kalder","CD93",,
"Santana","Maria, Maria","CD93",,
"Sash!","Stay","CD94",,
"Sash!","Ecuador","CD94",,
"Sash!","Encore Une Fois (Future Breeze","CD94",,
"Sash!","Mysterious Times","CD94",,
"Savage Garden","To the Moon & Back","CD94",,
"Savage Garden","Truly Madly Deeply","CD94",,
"Savage Garden","Crash and burn","CD94",,
"Savage Garden","The animal song","CD94",,
"Savage Garden","Affirmation","CD94",,
"Savage Rose","Black Angel","CD94",,
"Saybia","The second you sleep","CD94",,
"Scatman John","Scatman(Ski-ba Bop-ba Dop-b…","CD94",,
"Scissor Sisters","Take Your Mama Out","CD94",,
"Scissor Sisters","I Don't Feel Like Dancing","CD94",,
"Scooter","The Logical Song","CD94",,
"Scorpions","Rock You Like A Hurricane","CD95",,
"Scorpions","Send Me an Angel","CD95",,
"Scorpions","Wind of Change","CD95",,
"The Script","We Cry","CD95",,
"The Script","The Man Who Can't Be Moved","CD95",,
"Seal","Crazy","CD95",,
"Seal","Kiss From A Rose","CD95",,
"Seal","Killer","CD95",,
"Sean Paul","Get Busy","CD95",,
"Sebastian","Ostesangen","CD95",,
"Sebastian/Lis sørensen","Stille før storm","CD95",,
"Seether","Broken","CD95",,
"Seether","The Gift","CD95",,
"Selvmord","Råbe Under Vand","CD96",,
"Selvmord","OK","CD96",,
"September","Cry For You (UK Radio Edit)","CD96",,
"Shaft","(Mucho Mambo) Sway","CD96",,
"Shaggy","Boombastic","CD96",,
"Shaggy","Carolina","CD96",,
"Shaggy","Mr. Lover","CD96",,
"Shaggy","Sexual Healing","CD96",,
"Shaggy","Sexy Lady","CD96",,
"Shaggy","It Wasn't Me","CD96",,
"Shakira","Objection (Tango)","CD96",,
"Shakira","Whenever, Wherever","CD96",,
"Shakira","Hips Don't Lie","CD96",,
"Shania Twain","I'm Gonna Getcha Good!","CD96",,
"Shania Twain","Ka-Ching!","CD96",,
"Shanks & Bigfoot","Sweet Like Chocolate","CD97",,
"Sheryl Crow","Change Would Do You Good","CD97",,
"Sheryl Crow","If It Makes You Happy","CD97",,
"Sheryl Crow","Everyday Is a Winding Road","CD97",,
"Sheryl Crow","Run Baby Run","CD97",,
"Sheryl Crow","Leaving Las Vegas","CD97",,
"Sheryl Crow","All I Wanna Do Is Have Some…","CD97",,
"Shontelle","Impossible (Main)","CD97",,
"Shubidua","Askepot","CD97",,
"Shubidua","Den Røde Tråd","CD97",,
"Shubidua","Familien kom til kaffe","CD97",,
"Shubidua","Hvalen Valborg","CD97",,
"Shubidua","Sexchikane","CD97",,
"Shubidua","Stærk Tobak","CD97",,
"Shubidua","Vuffelivov","CD97",,
"Sia","Breathe Me","CD98",,
"Simon & Garfunkel","Mrs.Robinson","CD98",,
"Simple Minds","Don't You  (Forget About Me)","CD98",,
"Simple Minds","She's A River","CD98",,
"Simply Red","Fairground","CD98",,
"Sir Mix-A-Lot","Baby Got Back","CD98",,
"Sister Sledge","We Are Family","CD98",,
"Sixpence None the Richer","Kiss Me","CD98",,
"Sko & Torp","On a Long Lonely Night","CD98",,
"Skunk Anansie","Weak","CD98",,
"Smash Mouth","Why Can't We Be Friends","CD98",,
"Smash Mouth","Walking on the Sun","CD98",,
"Smash Mouth","I'm a Believer","CD98",,
"Smash Mouth","All Star","CD98",,
"Smashing Pumpkins","Tonight, Tonight","CD99",,
"Smashing Pumpkins","Bullet With Butterfly Wings","CD99",,
"Smashing Pumpkins","1979","CD99",,
"Smokie","Living next door to Alice","CD99",,
"Snap","Rythm is a Dancer","CD99",,
"Snap","I Got the Power","CD99",,
"Snapshot","Gi'r du et knus","CD99",,
"Sneakers","Sui Sui","CD99",,
"Snoop / Pharell","Beautiful","CD99",,
"Snoop Dog","Drop It Like It's Hot","CD99",,
"Snow","Informer","CD99",,
"Snow Patrol","Chasing Cars","CD99",,
"Snow Patrol","Just Say Yes","CD99",,
"Soko","I'll Kill Her","CD99",,
"Sonny & Cher","I Got You Babe","CD99",,
"Sort Sol","Let your fingers do the walking","CD99",,
"Soul Asylum","Runaway Train","CD100",,
"Sound Of Seduction","Welcome (Into My World)","CD100",,
"Sound of Seduction","Feel Like Dancin'","CD100",,
"Soundgarden","Black Hole Sun","CD100",,
"spacejam/B Real, Busta Rhym…","Hit 'Em High (The Monstars' A…","CD100",,
"Spice Girls","Wannabe","CD100",,
"Spice Girls","Viva Forever","CD100",,
"Spiller","Groovejet (If This Aint Love)","CD100",,
"Spin Doctors","Two Princess","CD100",,
"Spleen United","Spleen United","CD100",,
"Starship","Nothing's Gonna Stop Us Now","CD100",,
"Status Quo","You're in the Army Now","CD100",,
"Steppenwolf","Born To Be Wild","CD100",,
"Steppeulvene","0-0-0","CD100",,
"Steppeulvene","Itsi-Bitsi","CD100",,
"Stereophonics","Dakota","CD100",,
"Stereophonics","Maybe Tomorrow","CD100",,
"Steve Miller Band","The Joker","CD100",,
"Stevie Wonder","Master Blaster (Jammin')","CD101",,
"Stevie Wonder","I Just Called to Say I Love You","CD101",,
"Stevie Wonder","Isn't She Lovely","CD101",,
"Stevie Wonder","Superstition","CD101",,
"Stevie Wonder","You Are The Sunshine Of My Lif","CD101",,
"Stevie Wonder","For Once In My Life","CD101",,
"Stevie Wonder","Redemption Song","CD101",,
"Stevie Wonder","As","CD101",,
"Stevie Wonder","Happy Birthday","CD101",,
"Stevie Wonder","I Just Called To Say I Love Yo","CD101",,
"Stevie Wonder","I Wish","CD101",,
"Stevie Wonder","Master Blaster (Jammin)","CD101",,
"Stevie Wonder","Signed Sealed Delivered Im You","CD101",,
"Stevie Wonder","Sir Duke","CD101",,
"Stig Møller","Sikke'n dejlig dag","CD102",,
"Stone Temple Pilots","Plush","CD102",,
"The Streets","blinded by the lights","CD102",,
"The Streets","Dry Your Eyes","CD102",,
"The Streets","Fit, But Your Know It","CD102",,
"The Strokes","Last Nite","CD102",,
"Stromae","Alors on Danse","CD102",,
"Suede","Trash","CD102",,
"Suede","Beautiful Ones","CD102",,
"Sugababes","Get Sexy  (Radio Edit)","CD102",,
"Sugababes","Push the Button","CD102",,
"Sugababes","Round Round","CD102",,
"Sugarhill Gang","Rappers Delight","CD102",,
"Sukkerchok","Hvor Som Helst - Når Som Helst","CD102",,
"Superfunk feat. Ron Carroll","Lucky Star","CD102",,
"Surfact","Soulslide","CD103",,
"Surfact","Sugarcane","CD103",,
"Surfact","Step into the light","CD103",,
"Surfact","Absolutely Shameless","CD103",,
"Survivor","Eye of the Tiger","CD103",,
"Suspekt","Sut Den Op Fra Slap (Artmus…","CD103",,
"Suspekt","Kinky Faetter","CD103",,
"Suspekt","Kinky Fætter","CD103",,
"Suspekt","Hvem er en Kælling","CD103",,
"Svenstrup Og Vendelboe Feat.…","I Nat","CD103",,
"Switchfoot","Meant to Live","CD103",,
"SWV","Right Here","CD103",,
"Sys Bjerre","Alle Mine Veninder","CD103",,
"Sys Bjerre","Kegle","CD103",,
"Sys Bjerre","Malene","CD103",,
"System of a Down","Toxicity","CD103",,
"Szhirley","Glor På Vinduer","CD104",,
"Søren Kragh Jakobsen","Kender Du Det (Mona Mona M…","CD104",,
"Søs Fenger","Inderst inde","CD104",,
"Søs Fenger","Hvor End Jeg Går Hen","CD104",,
"Søs Fenger","Kun Et Kys Herfra","CD104",,
"Søs Finger, Thomas Helmig, S…","Den jeg elsker","CD104",,
"T.I Ft Justin Timberlake","Dead And Gone","CD104",,
"T.I.","Whatever You Like","CD104",,
"T.I. feat.Rihanna","Live Your Life","CD104",,
"Tag Team","Whoomp","CD104",,
"Taio Cruz","Dynamite","CD104",,
"Taio Cruz Ft. Ludacris","Break Your Heart","CD104",,
"Take That","Patience","CD105",,
"Take That","Reach Out","CD105",,
"Take That","Everything Changes","CD105",,
"Take That","Relight My Fire","CD105",,
"Take That","Pray","CD105",,
"Take That","Back for Good","CD105",,
"Talk Talk","It's My Life","CD105",,
"The Tamperer feat. Maya","Feel It","CD105",,
"Tatu","All the Things She Said","CD105",,
"Taylor Dayne","Can't Get Enough Of Your Love","CD105",,
"Technotronic","Pump The Jam","CD105",,
"Teddy Edelmann","Himmelhunden","CD105",,
"TEMA","Postmand Per","CD106",,
"TEMA","Top Gun Theme","CD106",,
"TEMA/BC52s","(Meet) The Flintstones","CD106",,
"TEMA/Beverly Hills Cop","Axel Foley Theme","CD106",,
"TEMA/Bruce Willis/pulp fiction","Zed's Dead, Baby [Dialogue]","CD106",,
"TEMA/C.W. McCall","Convoy","CD106",,
"TEMA/Dansk top","Øl, øl og mere øl","CD106",,
"TEMA/Danske Fodboldfans","Der er et yndigt land","CD106",,
"TEMA/Diverse","Selv En Dråbe","CD106",,
"TEMA/Diverse","Afrika","CD106",,
"TEMA/Diverse","50'er, 60'er og 70'er mix","CD106",,
"TEMA/Diverse","Hvor Små Vi Er","CD106",,
"TEMA/Jerrold Immel","Dallas","CD106",,
"TEMA/John E. Davis","Beverly Hills 90210","CD106",,
"TEMA/jungle book","The Bare Necessities","CD107",,
"TEMA/jungle book","I Wanna Be Like You","CD107",,
"TEMA/Lalo Schifrin","Mission Impossible","CD107",,
"TEMA/Landsholdet/Søren Pop…","Danmarks Drenge","CD107",,
"TEMA/Lille Per","Jeg har Set en Rigtig Negermand","CD107",,
"TEMA/LiON kING","Circle of Life","CD107",,
"TEMA/LiON kING","Hakuna Matata (tysk)","CD107",,
"TEMA/LiON kING","Can You Feel the Love Tonight","CD107",,
"TEMA/LiON kING","Hakuna Matata","CD107",,
"TEMA/LiON kING","I Just Can't Wait to be King","CD107",,
"TEMA/LiON sleeps tonight","In the Jungle","CD107",,
"TEMA/Movie Theme","Star Wars","CD107",,
"TEMA/Movie Theme","2001 Space Odyssey","CD107",,
"TEMA/Movie Theme","Indiana Jones","CD107",,
"TEMA/PULP FICTION","Pumpkin and Honey Bunny (Di…","CD107",,
"TEMA/Randy Edelman","MacGyver","CD108",,
"TEMA/Ray Parker Jr.","Ghostbusters","CD108",,
"TEMA/Ray Parker Jr.","Ghostbusters (Instr. Version)","CD108",,
"TEMA/Sam's Bar","Cheers","CD108",,
"TEMA/Tarzan","You'll be in my Heart","CD108",,
"TEMA/Thats all folks","That's All Folks","CD108",,
"TEMA/The A Team","The A Team Theme","CD108",,
"TEMA/Toy Story","You Got a Friend in Me","CD108",,
"TEMA/VM Holdet","Re-Sepp-Ten (Vi er røde, vi er…","CD108",,
"Temptations","Aint No Mountain High Enough","CD109",,
"Temptations","Build Me Up Buttercup","CD109",,
"The Temptations","My Girl","CD109",,
"Tenacious D","Fuck Her Gently","CD109",,
"Tenacious D","Tribute","CD109",,
"Texas","Say What You Want","CD109",,
"Texas","Summer Son","CD109",,
"Thin Lizzy","Boys Are Back in Town","CD109",,
"Thomas Helmig","Giv Mig Din Mund","CD109",,
"Thomas Helmig","Kære maskine","CD109",,
"Thomas Helmig","100 Dage (Feat. Medina)","CD109",,
"Thomas Helmig","Den Eneste Ene","CD109",,
"Thomas Helmig","Det er Mig Der Står Herude og…","CD109",,
"Thomas Helmig","Nu Hvor Du Har Brændt Mig Af","CD109",,
"Thomas Helmig","Stupid Man","CD109",,
"Thomas Helmig","Groovy Day","CD109",,
"Thomas Helmig","Dagen efter dagen derpå","CD109",,
"Thomas Helmig & Hanne Boel","Talk It Out","CD109",,
"Thomas Helmig og KNA Conn…","Det' Du Kan","CD109",,
"Thomas Holm","Nitten","CD110",,
"Tight Fit","The Lion Sleeps Tonight","CD110",,
"Tim Christensen","Whispering at the Top of My Lu…","CD110",,
"Tim Christensen","Right Next to the Right One","CD110",,
"Tim Christensen","Love Is A Matter Of...","CD110",,
"Timbaland","Give It To Me (Feat. Nelly Furt…","CD110",,
"Timbaland","Way I Are (Feat. Keri Hilson &…","CD110",,
"Timbaland","Night Rider","CD110",,
"Timbuktu","Alle Vil Till Himmelen, Men Ing…","CD110",,
"Tina Dickow","Open Wide","CD110",,
"Tina Turner","What's Love Got to Do With It","CD110",,
"Tina Turner","Simply The Best","CD110",,
"The Ting Tings","That's Not My Name","CD110",,
"The Ting Tings","Shut Up And Let Me Go","CD110",,
"TLC","No Scrubs","CD110",,
"TLC","Unpretty","CD110",,
"Tom Jones","If I Only Knew","CD111",,
"Tom Jones","Sexbomb (dancemix)","CD111",,
"Tom Jones","What's New Pussycat","CD111",,
"Tom Jones","Black Betty","CD111",,
"Tom Jones","Burning Down the House","CD111",,
"Tom Petty & the Heartbreakers","Free Fallin'","CD111",,
"Tom Petty & the Heartbreakers","Learning to Fly","CD111",,
"Tommy Seebach","Disko Tango","CD111",,
"Tommy Seebach","Hip Hurra Det' Min Fødselsdag","CD111",,
"Tommy Seebach og A. Heick","Du skælder mig hele tiden ud","CD111",,
"Tone Loc","Wild Thing","CD111",,
"Tone-Loc meets ZZ-Bros.","Funky Cold Medina 'Y2K","CD111",,
"Toni Braxton","You're Makin' Me High","CD111",,
"Toni Braxton","Un-Break My Heart","CD111",,
"Tony Christie","Amarillo","CD111",,
"Toploader","Dancing in the Moonlight","CD112",,
"Toploader","Just Hold On","CD112",,
"Toto","Africa","CD112",,
"Toto","Hold the Line","CD112",,
"Toto","Rosanna","CD112",,
"Touch And Go","Would you??(go to bed with me)","CD112",,
"Tracy Chapman","Talkin' Bout a Revolution","CD112",,
"Tracy Chapman","Fast Car","CD112",,
"Tracy Chapman","Baby Can I Hold You","CD112",,
"Train","Hey, Soul Sister","CD112",,
"The Trammps","Disco Inferno","CD112",,
"Travie Mccoy Ft. Bruno Mars","Billionaire","CD112",,
"Trax","Du er fuld af løgn","CD112",,
"Trentemøller","Moan","CD112",,
"Trine Dyrholm","Danse I Måneskin","CD112",,
"Trolle/siebenhar","sweet dogs","CD113",,
"Trolle/siebenhar","these streets","CD113",,
"Trucks","It's Just Porn Mom","CD113",,
"Tue West","Hun er Fri","CD113",,
"Tue West","En Sang om Kærlighed","CD113",,
"TV2","Alt Hvad Hun Ville Var","CD113",,
"TV2","De Første Kærester På Månen","CD113",,
"TV2","Der Går Min Klasselærer","CD113",,
"TV2","Det Er Samfundets Skyld","CD113",,
"TV2","Kom Lad Os Brokke Os","CD113",,
"TV2","Nærmest Lykkelig","CD113",,
"TV2","Be Bob Balula","CD113",,
"Twisted Sister","I Wanna Rock","CD113",,
"Tæskeholdet","Fredagssangen","CD113",,
"Tæskeholdet","Hesteluderen","CD113",,
"Tøsedrengene","Indianer","CD113",,
"Tøsedrengene","Vi Var Engang Så Tæt","CD113",,
"Tøsedrengene","Sig Du Kan Li' Mig","CD113",,
"U$O","Ingen Diskussion Feat. L.O.C…","CD113",,
"U2","Even Better Than The Real Thin","CD114",,
"U2","One","CD114",,
"U2","Mysterious Ways","CD114",,
"U2","Elevation","CD114",,
"U2","Pride (In the Name of Love)","CD114",,
"U2","Sunday Bloody Sunday","CD114",,
"U2","Desire","CD114",,
"U2","Beautiful Day","CD114",,
"U2","Hold Me, Thrill Me, Kiss Me, Ki…","CD114",,
"U2","Discotheque","CD114",,
"U2","Vertigo","CD114",,
"U2","I'll Go Crazy If I Don't Go Craz…","CD114",,
"UB40","(I Can't Help) Falling In Love…","CD115",,
"UB40","Red Red Wine","CD115",,
"UB40","Baby I Love Your Way","CD115",,
"UB40","Kingston Town","CD115",,
"UB40 and The Pretenders","I Got You Babe","CD115",,
"Ufo & Yepha","Op Med Håret","CD115",,
"Ufo & Yepha","Fluen På Væggen","CD115",,
"Ufo & Yepha feat. Natasja og B…","Hængekøjen","CD115",,
"Ufo & Yepha, Alex Brown,Ham…","Skub Til Taget","CD115",,
"Ugly Kid Joe","Cats In The Cradle","CD115",,
"Ugly Kid Joe","Everything About You","CD115",,
"Ugly Kid Joe","Mr. Recordman","CD115",,
"Ugly Kid Joe","Candle Song","CD115",,
"The Underdog Project","Summerjam","CD115",,
"Urge Overkill","Girl, You'll Be a Woman Soon","CD115",,
"Usher","Yeah","CD116",,
"Usher","DJ Got Us Falling In Love","CD116",,
"Usher","OMG","CD116",,
"Usher","You Make Me Wanna","CD116",,
"Usher","U Remind Me","CD116",,
"Van Halen","Jump","CD116",,
"Van Halen","You Really Got Me","CD116",,
"Van McCoy","Do the Hustle","CD116",,
"Van Morrison","Brown Eyed Girl","CD116",,
"Vanessa Williams","Colours of the Wind (Pocahont…","CD116",,
"Vanilla Ice","Ice Ice Baby","CD116",,
"Vasco & Millboy feat. Marbella","Sommartider","CD116",,
"Vengaboys","We're Going To Ibiza!","CD116",,
"Vengaboys","Shalala Lala","CD116",,
"Vengaboys","Boom Boom Boom Boom","CD116",,
"Veronica Maggio","Måndagsbarn","CD117",,
"The Verve","Love Is Noise","CD117",,
"The Verve","Bittersweet Symphony","CD117",,
"The Verve","The drugs don't work","CD117",,
"The Verve Pipe","Bittersweet Symphony","CD117",,
"Vica","Beatet i Mit Hjerte","CD117",,
"Village People","In the Navy","CD117",,
"Village People","Macho Man","CD117",,
"Village People","YMCA","CD117",,
"En Vogue","Don't Let Go (Love)",,,
"En Vogue","Lies",,,
"En Vogue","Free Your Mind",,,
"En Vogue","Don't Let Go [Love]",,,
"En Vogue","Whatta Man",,,
"En Vogue With Salt'n'Pepa","Whatta Man",,,
"Volbeat","The Garden`s Tale","CD117",,
"Volbeat","Sad Man`s Tongue","CD117",,
"Walking on Broken Glass","Annie Lennox","CD117",,
"Warrant","Cherry Pie","CD117",,
"Warren G and Nate Dogg","Regulate","CD117",,
"We Did","Swamp Thing","CD117",,
"Weather Girls","It's Raining Men","CD117",,
"Weezer","My Name is Jonas","CD118",,
"Weezer","Buddy Holly","CD118",,
"Weezer","Undone -- The Sweater Song […","CD118",,
"Westlife","Uptown Girl","CD118",,
"Westlife","World of Our Own","CD118",,
"Westlife","When You're Looking Like That","CD118",,
"Wet Wet Wet","Love Is All Around","CD118",,
"Wham!","Wake Me Up Before You Go-Go","CD118",,
"Wham!","Freedom","CD118",,
"Wham!","Careless Whisper","CD118",,
"Wham!","Club Tropicana","CD118",,
"Wham!","I'm Your Man","CD118",,
"Wham!","Last Christmas","CD118",,
"Wheatus","Teenage Dirtbag","CD118",,
"Whigfield","Saturday Night","CD118",,
"The White Stripes","Seven Nation Army","CD119",,
"Whitesnake","Life is a Highway","CD119",,
"Whitesnake","Here I Go Again","CD119",,
"Whitney Houston","I Wanna Dance With Somebody","CD119",,
"Whitney Houston","My Love Is Your Love","CD119",,
"Whitney Houston","I'm Every Woman","CD119",,
"Whitney Houston","I Wanna Dance With Somebod…","CD119",,
"Whitney Houston","How Will I Know","CD119",,
"The Who","My Generation","CD119",,
"Whoopi Goldberg","Shout","CD119",,
"Wildchild","Renegade Master 98","CD119",,
"Will Smith","Boom Shake The Room","CD119",,
"Will Smith","Gettin Jiggy With It","CD119",,
"Will Smith","Men In Black","CD119",,
"Will Smith","Miami","CD119",,
"Will Smith","Summertime","CD119",,
"Will Smith","Wild Wild West","CD119",,
"Womack And Womack","Teardrops","CD120",,
"Wyclef Jean","Ghetto Superstar","CD120",,
"Wyclef Jean","Perfect Gentleman","CD120",,
"Wyclef Jean","Electric Avenue","CD120",,
"Xtreme","More Than Words","CD120",,
"Yazz And The Plastic Population","The Only Way Is Up","CD120",,
"Yes","Owner of a Lonely Heart","CD120",,
"Yolanda Be Cool","Afro Nuts","CD120",,
"Yolanda Be Cool & Dcup","We No Speak Americano","CD120",,
"Yvonne Ellimon","If I Can't Have You","CD120",,
"Zapp Zapp","You Better Believe","CD120",,
"ZZ Top","Gimme All Your Lovin'","CD120",,
"Østkyst Hustlers","Han Får For Lidt","CD121",,
"Østkyst Hustlers","Jazzys Gambit",,,
"Østkyst Hustlers","Bossys Gambit",,,
"Østkyst Hustlers","Nedtur",,,
"Østkyst Hustlers","Gamle Homies",,,
"Østkyst Hustlers","98 Oktan Bly",,,
"Østkyst Hustlers","Hustleroverfarten",,,
"Østkyst Hustlers","Ankomst",,,
"Østkyst Hustlers","Diskohuset",,,
"Østkyst Hustlers","Balladesild",,,
"Østkyst Hustlers","Indbrud",,,
"Østkyst Hustlers","Randers By Night",,,
"2 Brothers On the 4th Floor","Dreams (Will Come Alive)","CD121",,
"2 Cowboys","Everybody Gonfi Gon","CD121",,
"2 Unlimited","No Limit","CD121",,
"2Pac","Changes","CD121",,
"2Pac","California Love","CD121",,
"3 Doors Down","Kryptonite","CD121",,
"4 Non Blondes","Whats Up","CD121",,
"5ive","If Ya Gettin' Down","CD121",,
"5ive","Slam Dunk (Da Funk)","CD121",,
"20 Fingers","Short Dick Man","CD121",,
"30 Seconds to Mars","The Kill","CD121",,
"30 Seconds to Mars","From Yesterday","CD121",,
"45 Degrees","Everything u want","CD122",,
"50 Cent","Candy Shop","CD122",,
"50 Cent","In Da Club","CD122",,
"50 Cent","P.I.M.P","CD122",,
"50 cent feat. Justin Timberlake","She Wants It","CD122",,
"50 Cent Ft. Ne-Yo","Baby By Me","CD122",,
"666","Bomba","CD122",,
"740 Boys","Shimmy Shake","CD122",,
];
